var WORDS = [ 




{ko:"아우", vi:"Em trai (cách gọi thân mật), Younger brother"},
{ko:"노래", vi:"Bài hát, Song"},
{ko:"노래하다", vi:"Hát, Sing"},
{ko:"나라", vi:"Đất nước / quốc gia, Country / Nation"},
{ko:"베개", vi:"Gối, Pillow"},
{ko:"조개", vi:"Sò / nghêu, Shellfish / Clam"},
{ko:"시계", vi:"Đồng hồ, Clock / Watch"},
{ko:"뉴스", vi:"Tin tức, News"},
{ko:"유리", vi:"Thủy tinh / kính, Glass"},
{ko:"꼬리", vi:"Đuôi, Tail"},
{ko:"공", vi:"Quả bóng, Ball"},
{ko:"개다", vi:"Gấp (quần áo, chăn), Fold"},
{ko:"깨다", vi:"Đập vỡ / tỉnh dậy, Break / Wake up"},
{ko:"캐다", vi:"Đào / khai thác (khoai, khoáng sản), Dig / Harvest"},
{ko:"비다", vi:"Trống / rỗng, Empty"},
{ko:"지다", vi:"Lặn / thua / gánh, Set / Lose / Carry"},
{ko:"찌다", vi:"Hấp / tăng cân, Steam / Gain weight"},
{ko:"대학원생", vi:"Nghiên cứu sinh / học viên cao học, Graduate student"},
{ko:"벼", vi:"Lúa, Rice plant"},
{ko:"파리", vi:"Con ruồi, Fly"},
{ko:"우표", vi:"Tem thư, Postage stamp"},
{ko:"코트", vi:"Áo khoác dài / sân (thể thao), Coat / Court"},
{ko:"기차표", vi:"Vé tàu hỏa, Train ticket"},
{ko:"뜨다", vi:"Nổi / mọc (mặt trời) / mở to (mắt), Rise / Float / Open"},
{ko:"허리띠", vi:"Thắt lưng, Belt"},
{ko:"뿌리", vi:"Rễ (cây), Root"},
{ko:"짜다", vi:"Mặn / lên kế hoạch / vắt (nước), Salty / Plan / Squeeze"},
{ko:"가짜", vi:"Giả / giả mạo, Fake"},
{ko:"곧", vi:"Sắp / ngay, Soon"},
{ko:"빗", vi:"Cái lược, Comb"},
{ko:"찜질방", vi:"Phòng xông hơi, Sauna"},
{ko:"노래방", vi:"Phòng karaoke, Karaoke room"},
{ko:"낮잠", vi:"Giấc ngủ trưa, Nap"},
{ko:"전쟁기념관", vi:"Bảo tàng chiến tranh, War memorial museum"},
{ko:"참", vi:"Thật là / rất / đúng là, Really / Truly"},
{ko:"복", vi:"Phúc / may mắn, Luck / Blessing"},
{ko:"복잡하다", vi:"Phức tạp / đông đúc, Complicated / Crowded"},
{ko:"중", vi:"Trong / đang, During / In"},
{ko:"이제", vi:"Bây giờ / từ nay, Now"},
{ko:"지금", vi:"Ngay bây giờ, Right now"},
{ko:"세게", vi:"Mạnh / mạnh mẽ, Strongly"},
{ko:"대왕", vi:"Đại vương, vua, Great king / Giant"},
{ko:"동상", vi:"Tượng, Statue"},
{ko:"단축키", vi:"Phím tắt, Shortcut key"},
{ko:"유용", vi:"Sự hữu ích, Usefulness"},
{ko:"유용하다", vi:"Hữu ích, Useful"},
{ko:"제목", vi:"Tiêu đề, Title"},
{ko:"나열", vi:"Sự liệt kê, Listing"},
{ko:"양", vi:"Số lượng / con cừu, Amount / Sheep"},
{ko:"찜통", vi:"Nồi hấp / phòng nóng, Steamer"},
{ko:"크리스마스", vi:"Lễ Giáng Sinh, Christmas"},
{ko:"축제", vi:"Lễ hội, Festival"},
{ko:"진급", vi:"Thăng cấp, Promotion"},
{ko:"집들이", vi:"Tiệc tân gia, Housewarming"},
{ko:"입학", vi:"Nhập học, Admission"},
{ko:"아메리카노", vi:"Cà phê Americano, Americano coffee"},
{ko:"구이", vi:"Món nướng, Grilled dish"},
{ko:"바비큐", vi:"Thịt nướng BBQ, Barbecue"},
{ko:"조식", vi:"Bữa sáng (khách sạn), Breakfast"},
{ko:"중식", vi:"Bữa trưa / Bữa ăn phong cách Trung Hoa, Lunch / Chinese meal"},
{ko:"석식", vi:"Bữa tối, Dinner"},
{ko:"양고기", vi:"Thịt cừu, Lamb"},
{ko:"겨자", vi:"Mù tạt, Mustard"}, 
{ko:"뱀", vi:"Con rắn, Snake"},
{ko:"모기", vi:"Con muỗi, Mosquito"},
{ko:"하마", vi:"Hà mã, Hippopotamus"},
{ko:"여우", vi:"Con cáo, Fox"},
{ko:"쥐", vi:"Con chuột, Mouse / Rat"}, 
{ko:"도와드리다", vi:"Giúp (kính ngữ), Help (honorific)"},
{ko:"따라하다", vi:"Làm theo / bắt chước, Imitate"},
{ko:"발음", vi:"Phát âm, Pronunciation"},
{ko:"소리", vi:"Âm thanh, Sound"},
{ko:"복도", vi:"Hành lang, Corridor"},
{ko:"바꾸다", vi:"Thay đổi / đổi, Change"},
{ko:"비우다", vi:"Làm trống / dọn trống, Empty"},  
{ko:"이사", vi:"Việc chuyển nhà, Moving"},
{ko:"이사하다", vi:"Chuyển nhà, Move house"},
{ko:"경찰서", vi:"Đồn cảnh sát, Police station"},
{ko:"센터", vi:"Trung tâm, Center"},
{ko:"서비스센터", vi:"Trung tâm dịch vụ, Service center"},
{ko:"이삿짐센터", vi:"Công ty chuyển nhà, Moving service"},
{ko:"고객센터", vi:"Trung tâm chăm sóc khách hàng, Customer center"}, 
{ko:"바닥", vi:"Sàn nhà, Floor"},
{ko:"온돌", vi:"Sưởi sàn Hàn Quốc, Ondol heating"},
{ko:"보일러", vi:"Lò sưởi/ nồi hơi, Boiler"},
{ko:"히터", vi:"Máy sưởi, Heater"},
{ko:"에어컨", vi:"Điều hòa, Air conditioner"},
{ko:"이불", vi:"Chăn, Blanket"},
{ko:"가구", vi:"Đồ nội thất, Furniture"}, 
{ko:"감기", vi:"Cảm lạnh, Cold"},
{ko:"푹", vi:"Sâu / kỹ / hoàn toàn, Deeply / Well"},
{ko:"건조하다", vi:"Khô, Dry"},
{ko:"위험", vi:"Nguy hiểm, Danger"},
{ko:"위험하다", vi:"Nguy hiểm, Dangerous"},
{ko:"더위", vi:"Nóng bức, Heat"},
{ko:"찜통 더위", vi:"Nóng như lò hấp, Sweltering heat"},  
{ko:"여보", vi:"Anh / em (gọi vợ/chồng), Honey / Dear"},
{ko:"실례", vi:"Xin lỗi / thất lễ, Excuse me / Rudeness"},
{ko:"싸우다", vi:"Cãi nhau / đánh nhau, Fight / Argue"},
{ko:"이상하다", vi:"Kỳ lạ, Strange"},
{ko:"이상", vi:"Trở lên, Above / Over"},  
{ko:"비슷하다", vi:"Giống, tương tự, Similar"},
{ko:"보험", vi:"Bảo hiểm, Insurance"},
{ko:"액션 영화", vi:"Phim hành động, Action movie"},
{ko:"멜로 영화", vi:"Phim tình cảm, Romance / Melodrama movie"},
{ko:"코미디 영화", vi:"Phim hài, Comedy movie"},
{ko:"공포 영화", vi:"Phim kinh dị, Horror movie"},
{ko:"SF 영화", vi:"Phim khoa học viễn tưởng, Science fiction movie"},
{ko:"음악", vi:"Âm nhạc, Music"},
{ko:"반대", vi:"Sự phản đối / đối lập, Opposition"},
{ko:"반대쪽", vi:"Phía đối diện, Opposite side"},
{ko:"반대말", vi:"Từ trái nghĩa, Antonym"},
{ko:"반대하다", vi:"Phản đối, Oppose"},
{ko:"급", vi:"Cấp / hạng, Level / Grade"},
{ko:"더럽다", vi:"Bẩn, Dirty"},
{ko:"따르다", vi:"Theo / làm theo / rót (đồ uống), Follow / Pour"},
{ko:"늙다", vi:"Già đi, Become old"},
{ko:"노인", vi:"Người già, Elderly person"},
{ko:"젊다", vi:"Trẻ / trẻ trung, Young"},
{ko:"냄새", vi:"Mùi, Smell / Odor"},
{ko:"맛", vi:"Vị / hương vị, Taste / Flavor"},
{ko:"가져가다", vi:"Mang đi, Take away"},
{ko:"계절", vi:"Mùa, Season"},
{ko:"고르다", vi:"Chọn, Choose / Select"},
{ko:"공기", vi:"Không khí, Air"},
{ko:"그렇다", vi:"Như vậy / đúng vậy, Be so / That is right"},
{ko:"기념/ 기념하다", vi:"Kỷ niệm, Commemorate / Celebrate"},
{ko:"기온", vi:"Nhiệt độ (không khí), Temperature"},
{ko:"길", vi:"Đường, Road / Way"},
{ko:"꽃", vi:"Hoa, Flower"},
{ko:"내리다", vi:"Xuống / rơi (mưa, tuyết), Get off / Fall"},
{ko:"너무", vi:"Quá / rất, Too / Very"},
{ko:"놀다", vi:"Chơi / vui chơi, Play / Hang out"},
{ko:"늦다", vi:"Muộn / trễ, Late"},
{ko:"다행이다", vi:"May mắn / thật may, Fortunately"},
{ko:"따뜻하다", vi:"Ấm áp, Warm"},
{ko:"막히다", vi:"Bị tắc / kẹt (xe), Be blocked / Traffic jam"},
{ko:"맑다", vi:"Trong (trời), Clear"},
{ko:"모르다", vi:"Không biết, Not know"},
{ko:"문제", vi:"Vấn đề / câu hỏi, Problem / Question"},
{ko:"미안하다", vi:"Xin lỗi, Sorry"},
{ko:"부치다", vi:"Gửi (bưu phẩm), Send / Mail"},
{ko:"비자", vi:"Visa"},
{ko:"사계절", vi:"Bốn mùa, Four seasons"},
{ko:"소포", vi:"Bưu kiện, Parcel"},
{ko:"소풍", vi:"Dã ngoại / picnic, Picnic"},
{ko:"술집", vi:"Quán rượu / quán nhậu, Bar / Pub"},
{ko:"습기", vi:"Độ ẩm, Humidity"},
{ko:"시원하다", vi:"Mát mẻ / sảng khoái, Cool / Refreshing"},
{ko:"싱싱하다", vi:"Tươi, Fresh"},
{ko:"야외", vi:"Ngoài trời, Outdoors"},
{ko:"야유회", vi:"Buổi dã ngoại / outing, Outing"},
{ko:"우의", vi:"Áo mưa, Raincoat"},
{ko:"이유", vi:"Lý do, Reason"},
{ko:"일기예보", vi:"Dự báo thời tiết, Weather forecast"},
{ko:"일찍", vi:"Sớm, Early"},
{ko:"잘하다", vi:"Làm tốt / giỏi, Do well"},
{ko:"잡지", vi:"Tạp chí, Magazine"},
{ko:"장마", vi:"Mùa mưa (monsoon), Rainy season"},
{ko:"전국", vi:"Toàn quốc, Nationwide"},
{ko:"제안하다", vi:"Đề nghị / đề xuất, Suggest / Propose"},
{ko:"좀", vi:"Một chút / hơi, A little"},
{ko:"질문하다", vi:"Đặt câu hỏi, Ask a question"},
{ko:"찾다", vi:"Tìm, Find / Look for"},
{ko:"최고/ 최저", vi:"Cao nhất / tốt nhất, Highest / Best/ Thấp nhất, Lowest"},
{ko:"특기", vi:"Sở trường / kỹ năng đặc biệt, Specialty"},
{ko:"피다", vi:"Nở (hoa), Bloom"},
{ko:"피서", vi:"Tránh nóng / nghỉ mát, Summer vacation / Escape the heat"},
{ko:"하늘", vi:"Bầu trời, Sky"},
{ko:"화장품", vi:"Mỹ phẩm, Cosmetics"},
{ko:"활짝", vi:"Nở rộ / mở to, Fully / Widely"},
{ko:"흐리다", vi:"U ám / nhiều mây, Cloudy"},
{ko:"지휘관", vi:"Chỉ huy, Commander"},
{ko:"감기에 걸리다", vi:"Bị cảm lạnh, Catch a cold"},
{ko:"같다", vi:"Giống y chang, Same"},
{ko:"교회", vi:"Nhà thờ, Church"},
{ko:"기다리다", vi:"Wait"},
{ko:"나중에", vi:"Sau này / lát nữa, Later"},
{ko:"난방/ 냉방", vi:"Sưởi ấm, Heating/ Làm mát, Air conditioning"},
{ko:"돌아오다", vi:"Trở về, Return / Come back"},
{ko:"무엇을 도와드릴까요?", vi:"Tôi có thể giúp gì cho bạn?, How may I help you?"},
{ko:"거짓", vi:"Giả dối / sai sự thật, False"},
{ko:"거짓말/ 거짓말하다", vi:"Nói dối, Lie/ To lie"},
{ko:"슬프다", vi:"Buồn, Sad"},
{ko:"데이트/ 데이트하다", vi:"Hẹn hò, Date/ To date"},
{ko:"나가다", vi:"Ra ngoài, Go out"},
{ko:"출타", vi:"Ra ngoài có phép, Authorized leave"},
{ko:"외출", vi:"Ra ngoài (có phép), Going out"},
{ko:"자유 시간", vi:"Thời gian tự do, Free time"},
{ko:"독서/ 독서하다", vi:"Đọc sách, Reading"},
{ko:"기차/ 기차역", vi:"Train/ Ga tàu hỏa, Train station"},
{ko:"금방", vi:"Ngay / chẳng mấy chốc, Soon / Quickly"},
{ko:"시설", vi:"Cơ sở vật chất, Facility"},
{ko:"설비", vi:"Trang thiết bị, Equipment"},
{ko:"이미지", vi:"Hình ảnh / hình tượng, Image"},
{ko:"수량", vi:"Số lượng, Quantity"},
{ko:"자신", vi:"Bản thân / sự tự tin, Oneself / Confidence"},
{ko:"만", vi:"10 nghìn/ 1 vạn/ Chỉ/ Nhưng"},
{ko:"실력", vi:"Năng lực / trình độ, Ability / Skill"},
{ko:"늘다", vi:"Tiến bộ / tăng lên, Improve / Increase"},
{ko:"구조", vi:"Cấu trúc, Structure"},
{ko:"음절", vi:"Âm tiết, Syllable"},
{ko:"격식", vi:"Sự trang trọng, Formality"},
{ko:"격식체", vi:"Thể trang trọng, Formal speech style"},
{ko:"비격식체", vi:"Thể không trang trọng, Informal speech style"},
{ko:"내용", vi:"Nội dung, Content"},
{ko:"기타", vi:"Vân vân, Etcetera/ Guitar"},
{ko:"잠자다", vi:"Sleep"},  
{ko:"자다/ 주무시다", vi:"Sleep (thường – kính ngữ)"},  
{ko:"취침/ 취침하다", vi:"Đi ngủ, Bedtime/Go to bed"}, 
{ko:"있다/ 계시다/ 있으시다", vi:"Có / ở (thường – kính ngữ)"},
{ko:"지폐/ 동전", vi:"Tiền giấy, Cash/ Tiền xu, Coin"},
{ko:"통화", vi:"Tiền tệ / gọi điện, Currency / Call"},
{ko:"개월", vi:"Tháng (đơn vị đếm), Month (counter)"},
{ko:"경영", vi:"Quản lý / kinh doanh, Management"},
{ko:"퇴직하다", vi:"Nghỉ hưu / thôi việc, Retire"},
{ko:"퇴임하다", vi:"Mãn nhiệm, Từ chức (chức vụ cao), Step down"},
{ko:"이시다", vi:"Là (kính ngữ của ‘이다’), Be (honorific)"},
{ko:"형제", vi:"Anh em, Siblings"},
{ko:"가족/ 가정", vi:"Gia đình/ Gia đình nhỏ, , Family"},
{ko:"갈아타다/ 환승/ 환승하다", vi:"Chuyển tuyến / đổi xe, Transfer"},
{ko:"호선", vi:"Tuyến (tàu điện), Line"},
{ko:"다르다", vi:"Different"},
{ko:"비교", vi:"So sánh, Compare"},
{ko:"땅", vi:"Đất / mặt đất, Land / Ground"},
{ko:"먹다/ 드시다", vi:"Ăn (thường / kính ngữ)"},
{ko:"능력", vi:"Năng lực, Ability"},
{ko:"기술", vi:"Kỹ thuật / kỹ năng, Skill / Technology"},
{ko:"재능", vi:"Tài năng, Talent"},
{ko:"부탁", vi:"Yêu cầu/ Nhờ vả, Request"},
{ko:"제안", vi:"Đề xuất, Suggestion"},
{ko:"의무", vi:"Nhiệm vụ, Duty / Obligation"},

{ko:"가깝다", vi:"Gần, Near"},
{ko:"걸리다", vi:"Mất (thời gian), Take (time)"},
{ko:"교통", vi:"Giao thông, Traffic"},
{ko:"대중교통", vi:"Giao thông công cộng, Public transport"},
{ko:"목적지/행선지", vi:"Điểm đến, Destination"},
{ko:"방법", vi:"Phương pháp / cách, Method / Way"},
{ko:"수단", vi:"Phương tiện, Means"},
{ko:"시내", vi:"Trong thành phố, Downtown"},
{ko:"시외", vi:"Ngoại ô, Suburbs"},
{ko:"사용하다", vi:"Sử dụng, Use"},
{ko:"이용하다", vi:"Sử dụng (dịch vụ, phương tiện), Utilize"},
{ko:"자가용", vi:"Xe riêng, Private car"},
{ko:"차량", vi:"Phương tiện / xe cộ, Vehicle"},
{ko:"터미널", vi:"Bến xe, Terminal"},
{ko:"KTX", vi:"Tàu cao tốc Hàn Quốc, High-speed train"},
{ko:"자리", vi:"Chỗ ngồi / vị trí, Seat / Place"},
{ko:"지역", vi:"Khu vực, Region"},
{ko:"지리", vi:"Địa lý, Geography"},
{ko:"쪽", vi:"Phía, hướng, trang, ..."},
{ko:"타워", vi:"Tháp, Tower"},
{ko:"경복궁", vi:"Cung Gyeongbok, Gyeongbokgung Palace"},
{ko:"남산", vi:"Núi Namsan, Namsan"},
{ko:"대전", vi:"Thành phố Daejeon, Daejeon"},
{ko:"대구", vi:"Thành phố Daegu, Daegu"},
{ko:"서울역", vi:"Ga Seoul, Seoul Station"},
{ko:"시청", vi:"Tòa thị chính, City Hall"},
{ko:"다행히", vi:"May mắn thay, Fortunately"},
{ko:"만들다", vi:"Làm / tạo ra, Make"},
{ko:"앉다", vi:"Ngồi, Sit"},
{ko:"어떻게", vi:"Như thế nào, How"},
{ko:"일어서다", vi:"Đứng lên, Stand up"},
{ko:"조용히", vi:"Yên lặng, Quietly"},
{ko:"함께", vi:"Cùng nhau, Together"},
{ko:"나", vi:"Tôi, I"},
{ko:"저희", vi:"Chúng tôi (khiêm nhường), We (humble)"},
{ko:"남동생", vi:"Em trai, Younger brother"},
{ko:"고모", vi:"Cô (bên nội), Paternal aunt"},
{ko:"고모부", vi:"Chồng của cô, Uncle by marriage"},
{ko:"외할머니", vi:"Bà ngoại, Maternal grandmother"},
{ko:"부부", vi:"Vợ chồng, Couple"},
{ko:"선배", vi:"Tiền bối, Senior"},
{ko:"사장/ 사장님", vi:"Giám đốc / chủ, Boss"},
{ko:"사원", vi:"Nhân viên, Employee"},
{ko:"대학생", vi:"Sinh viên đại học, University student"},
{ko:"경영학과", vi:"Khoa quản trị kinh doanh, Business administration"},
{ko:"교사/ 선생님/ 교수", vi:"Giáo viên, Teacher/ Professor"}, 
{ko:"단체", vi:"Tập thể / đoàn thể, Group"},
{ko:"말씀", vi:"Lời nói (kính ngữ), Words (honorific)"},
{ko:"생신", vi:"Sinh nhật (kính ngữ), Birthday (honorific)"},
{ko:"돌아가시다", vi:"Qua đời (kính ngữ), Pass away"},
{ko:"절하다", vi:"Cúi chào, Bow"},
{ko:"모양", vi:"Hình dạng, Shape"},
{ko:"변하다", vi:"Thay đổi, Change"},
{ko:"언제나", vi:"Luôn luôn, Always"},
{ko:"기뻐하다", vi:"Vui mừng, Be glad"},
{ko:"화가", vi:"Họa sĩ, Painter"},  
{ko:"곱다", vi:"Đẹp, mịn, dịu (màu sắc, da), Beautiful / Fine"},
{ko:"고맙다", vi:"Biết ơn / cảm ơn, Thankful"},
{ko:"반갑다", vi:"Vui mừng khi gặp, Glad / Nice to meet"}, 
{ko:"나열하다", vi:"Liệt kê, List / Enumerate"},
{ko:"서비스", vi:"Dịch vụ, Service"},
{ko:"불규칙", vi:"Bất quy tắc, Irregularity"},
{ko:"미래", vi:"Future"},
{ko:"들어봅시다", vi:"Hãy nghe thử nhé, Let's listen"},  
{ko:"보고 싶다", vi:"Want to see / Miss"},  
{ko:"얻다", vi:"Nhận được / đạt được, Obtain / Get"},   
{ko:"품질", vi:"Quality"},
{ko:"날짜", vi:"Ngày tháng, Date"},
{ko:"순차", vi:"Theo thứ tự, Sequence"}, 
{ko:"달", vi:"Month / Moon"},
{ko:"번", vi:"Lần,số, Time"},
{ko:"발", vi:"Foot"},

{ko:"키", vi:"Chiều cao / chìa khóa, Height / Key"},
{ko:"계속", vi:"Liên tục, Continuously"},
{ko:"그렇지만", vi:"However"},
{ko:"꼭", vi:"Nhất định / chắc chắn, Surely"},
{ko:"다시", vi:"Again"},
{ko:"또", vi:"Again / Also"},
{ko:"아직", vi:"Vẫn chưa, Still / Yet"},
{ko:"왜", vi:"Why"},
{ko:"내무반", vi:"Phòng sinh hoạt bộ đội, Barracks room"},
{ko:"지휘 본부/사령부", vi:"Bộ chỉ huy/ Bộ tư lệnh, Command headquarters"},
{ko:"검도", vi:"Kiếm đạo (Kendo), Kendo"},
{ko:"도장", vi:"Võ đường / con dấu, Dojo / Seal"},
{ko:"야구", vi:"Bóng chày, Baseball"},
{ko:"태권도", vi:"Taekwondo, Taekwondo"},
{ko:"기숙사", vi:"Ký túc xá, Dormitory"},
{ko:"비행기", vi:"Airplane"},
{ko:"주스", vi:"Juice"},
{ko:"표", vi:"Ticket"},
{ko:"복장", vi:"Trang phục, Outfit"},
{ko:"계획", vi:"Plan"},
{ko:"공격하다", vi:"Tấn công, Attack"},
{ko:"도와주다", vi:"Help"},
{ko:"나오다", vi:"Ra / xuất hiện, Come out"},
{ko:"따다", vi:"Hái / lấy / mở (nắp), Pick / Obtain"},
{ko:"모이다", vi:"Tập hợp, Gather"},
{ko:"방송하다", vi:"Phát sóng, Broadcast"},
{ko:"방어/ 방어하다/ 방어선", vi:"Phòng ngự/ Tuyến phòng ngự, Defend"},
{ko:"알리다", vi:"Thông báo, Inform"},
{ko:"예약하다", vi:"Đặt trước, Reserve"},
{ko:"오다", vi:"Come"},
{ko:"전화하다", vi:"Call"},
{ko:"조깅/ 조깅하다/ 뜀걸음/ 뜀걸음하다", vi:"Chạy bộ nhẹ, Jog"},
{ko:"취직하다", vi:"Xin được việc, Get a job"},
{ko:"집합하다", vi:"Tập hợp, Assemble"},
{ko:"가볍다", vi:"Light"},
{ko:"건강하다", vi:"Healthy"},
{ko:"부럽다", vi:"Ghen tị, Envious"},
{ko:"특별하다", vi:"Special"},
{ko:"힘들다", vi:"Mệt / vất vả, Tiring / Hard"},
{ko:"권", vi:"Quyển/cuốn"},
{ko:"대", vi:"Chiếc (máy móc, xe), Unit / Machine"},
{ko:"마리", vi:"Con (động vật), Animal counter"},
{ko:"박스", vi:"Box"},
{ko:"봉지", vi:"Túi (nilon, giấy), Bag"},
{ko:"벌", vi:"Bộ (quần áo), Set (clothes)"},
{ko:"병", vi:"Bottle"},
{ko:"송이", vi:"Bông/chùm (hoa, nấm), Bunch"},
{ko:"인분", vi:"Phần ăn (cho người), Serving"},
{ko:"자루", vi:"Cán, cây, cái, bao tải, Item / Sack"},
{ko:"장", vi:"Tờ (giấy, vé), Sheet"},
{ko:"켤레", vi:"Đôi (giày, tất), Pair"},
{ko:"토끼", vi:"Rabbit"},
{ko:"개", vi:"Dog"},
{ko:"공항", vi:"Airport"},
{ko:"지난주", vi:"Tuần trước, Last week"},   
{ko:"주다/ 드리다", vi:"Cho (thường / kính ngữ)"},
{ko:"주문하다", vi:"Đặt hàng / gọi món, Order"},
{ko:"동물/ 동물원", vi:"Động vật/ Sở thú, Zoo"},
{ko:"팔다", vi:"Bán, Sell"},
{ko:"기능", vi:"Chức năng, Function"},
{ko:"신다", vi:"Mang / đi (giày, tất), Wear (shoes/socks)"},
{ko:"공연", vi:"Buổi biểu diễn, Performance"},
{ko:"잔", vi:"Cốc / chén (đơn vị đếm), Cup / Glass (counter)"},
{ko:"잠시만", vi:"Đợi một chút nhé, Just a moment"},  
{ko:"가게", vi:"Cửa hàng, Shop"},
{ko:"가격", vi:"Giá cả, Price"},
{ko:"각각", vi:"Mỗi / từng cái, Each"},
{ko:"각자", vi:"Mỗi người / mỗi cái (tự riêng), Each person / each one"},
{ko:"경기", vi:"Trận đấu (thể thao), Game / Match"},
{ko:"경기장", vi:"Sân thi đấu / sân vận động, Stadium"},
{ko:"골프", vi:"Golf, Golf"},
{ko:"곰", vi:"Con gấu, Bear"},
{ko:"과자", vi:"Bánh kẹo, Snack"},
{ko:"귤", vi:"Quýt, Mandarine"},
{ko:"기분", vi:"Cảm xúc / tâm trạng, Feeling"},
{ko:"내다", vi:"Đưa ra / trả (tiền), Pay / Put out"},
{ko:"떡볶이", vi:"Bánh gạo cay, Tteokbokki"},
{ko:"맵다", vi:"Spicy"},
{ko:"먼저", vi:"Trước tiên, First"},
{ko:"문구점", vi:"Văn phòng phẩm, Stationery store"},
{ko:"반지", vi:"Nhẫn, Ring"},
{ko:"배", vi:"Pear / Belly / Boat"},
{ko:"사탕", vi:"Candy"},
{ko:"소주", vi:"Soju"},
{ko:"수학", vi:"Mathematics"},
{ko:"숫자", vi:"Con số, Number"},
{ko:"신발", vi:"Shoes"},
{ko:"아저씨", vi:"Chú / bác (nam), Mister / Uncle"},
{ko:"아주머니", vi:"Cô / bác (nữ), Aunt / Madam"},
{ko:"양말", vi:"Tất, Socks"},
{ko:"양복", vi:"Bộ vest, Suit"},
{ko:"어서", vi:"Nhanh lên / mời vào, Hurry / Please come"},
{ko:"억", vi:"One hundred million"},
{ko:"우산/ 양산", vi:"Ô che mưa/ Ô che nắng, Umbrella"},
{ko:"원", vi:"Won"},
{ko:"인형", vi:"Doll"},
{ko:"자동차", vi:"Car"},
{ko:"잠시", vi:"Một lát, A moment"},
{ko:"정말", vi:"Thật sự, Really"},
{ko:"조금", vi:"A little"},
{ko:"실패/ 실패하다", vi:"Thất bại, Failure/Thất bại, Fail"},
{ko:"통과/ 통과하다", vi:"Vượt qua / thông qua, Pass/Vượt qua / đậu (kỳ thi, kiểm tra), Pass"},
{ko:"성공/ 성공하다", vi:"Success/ Succeed"},
{ko:"탈락/ 탈락하다", vi:"Bị loại, lược bỏ, Elimination/Bị loại (thi cử, tuyển chọn), Be eliminated / Fail"},
{ko:"선물/ 선물하다", vi:"Gift/ Give a gift"},
{ko:"설거지", vi:"Rửa bát, Do the dishes"},
{ko:"돕다", vi:"Giúp đỡ, Help"},
{ko:"시험/ 시험하다", vi:"Kỳ thi / bài kiểm tra, Exam"},
{ko:"싫어하다", vi:"Ghét / không thích, Dislike"},
{ko:"그저께/ 어제/ 오늘/ 내일/ 모레", vi:"The day before yesterday/Yesterday/Today/Tomorrow/ The day after tomorrow"},
{ko:"박", vi:"Đêm / quả bầu, Night / Gourd"},
{ko:"얼마", vi:"Bao nhiêu / bao lâu, How much / How long"},
{ko:"여러", vi:"Nhiều, Several"},
{ko:"여러 가지", vi:"Nhiều loại, Various"},
{ko:"남다", vi:"Còn lại, Remain"},
{ko:"역사", vi:"Lịch sử, History"},
{ko:"오랜만", vi:"Lâu rồi (không gặp), Long time no see"},
{ko:"운동모/ 운동복/ 운동화/ 운동장", vi:"Sports cap/ Sportswear/ Sneakers/ Playground"},
{ko:"운동/ 운동하다", vi:"Exercise"},  
{ko:"면허증", vi:"Giấy phép / bằng lái, License"},
{ko:"이름나다", vi:"Nổi tiếng, Be well-known"},
{ko:"치과", vi:"Nha khoa, Dental clinic"},
{ko:"일기", vi:"Nhật ký/ Thời tiết, Diary/ Weather"},
{ko:"쯤", vi:"Khoảng chừng, About / Around"},
{ko:"초등", vi:"Tiểu học (viết tắt), Elementary"},
{ko:"지난", vi:"Đã qua / trước, Last / Past"},
{ko:"참", vi:"Thật là / đúng là, Really"},
{ko:"해변", vi:"Bãi biển, Beach"},
{ko:"해외", vi:"Nước ngoài, Overseas"},
{ko:"수도", vi:"Thủ đô, Capital city"},
{ko:"전쟁", vi:"Chiến tranh, War"},   
{ko:"사귀다", vi:"Hẹn hò / kết bạn, Date / Be friends"},
{ko:"사투리", vi:"Phương ngữ / tiếng địa phương, Dialect"},
{ko:"생활", vi:"Sinh hoạt / cuộc sống, Life / Living"},
{ko:"대양", vi:"Đại dương, Ocean"},
{ko:"후예", vi:"Hậu duệ, Descendant"},
{ko:"출근/ 출근하다", vi:"Đi làm, Commute, Go to work"},
{ko:"퇴근/ 퇴근하다", vi:"Tan làm, Leave work, Get off work"},
{ko:"첫", vi:"Đầu tiên, First"},
{ko:"첫눈", vi:"Tuyết đầu mùa / tình yêu sét đánh, First snow / Love at first sight"},
{ko:"첫날", vi:"Ngày đầu tiên, First day"},
{ko:"환호/ 환호하다", vi:"Hoan hô / reo hò, Cheer"},
{ko:"엄정/ 엄정하다", vi:"Nghiêm khắc, Strict"},
{ko:"태도", vi:"Thái độ, Attitude"},
{ko:"정리/ 정리하다", vi:"Sắp xếp, dọn dẹp, Organization/Organize"},
{ko:"친절하다", vi:"Thân thiện, Kind"},
{ko:"혼자", vi:"Một mình, Alone"},
{ko:"휴식", vi:"Nghỉ ngơi, Rest"},
{ko:"휴식하다", vi:"Nghỉ ngơi, Take a rest"},
{ko:"세면/ 세면하다", vi:"Rửa mặt, Washing up/ Wash face"},
{ko:"현장 학습", vi:"Học tập thực tế, Field trip"},
{ko:"점호/ 점호하다", vi:"Điểm danh, Call roll"},
{ko:"갈비/ 갈비탕", vi:"Sườn, Ribs/Canh sườn, Rib soup"},
{ko:"괜찮다", vi:"Ổn / không sao, Okay"},
{ko:"기념품", vi:"Quà lưu niệm, Souvenir"},
{ko:"김치찌개", vi:"Canh kimchi, Kimchi stew"},
{ko:"낚시/ 낚시하다/ 낚시터", vi:"Câu cá, Fishing/Go fishing/Fishing spot"},
{ko:"작년/ 금년(올/ 올해)/ 내년", vi:"Last year/This year (올 đứng trước danh từ, 올해 là danh từ)/Next year"},
{ko:"장년", vi:"Tuổi trung niên, Middle age"},
{ko:"냉면", vi:"Mì lạnh, Cold noodles"},
{ko:"녹색", vi:"Màu xanh lá, Green"},
{ko:"나뭇잎", vi:"Lá cây, Leaf"},
{ko:"다음", vi:"Tiếp theo, Next"},
{ko:"단풍", vi:"Lá đỏ mùa thu, Autumn leaves"},
{ko:"열다/ 닫다", vi:"Open/Close"},
{ko:"된장찌개", vi:"Canh tương đậu, Soybean paste stew"},
{ko:"인공/ 인조/ 인위", vi:"Nhân tạo / do con người tạo, Man-made"},
{ko:"색", vi:"Màu sắc, Color"},
{ko:"스키/ 스키장", vi:"Trượt tuyết, Ski/ Khu trượt tuyết, Ski resort"},
{ko:"죽다", vi:"Chết, Die"},
{ko:"아프다", vi:"Đau / bị bệnh, Sick"},
{ko:"역", vi:"Nhà ga, Station"},
{ko:"연락/ 연락하다", vi:"Liên lạc, Contact"},
{ko:"죄송하다", vi:"Xin lỗi (trang trọng), Sorry"},
{ko:"초대/ 초대하다", vi:"Lời mời, Invitation/ Mời, Invite"},
{ko:"탁구", vi:"Bóng bàn, Table tennis"},
{ko:"명동", vi:"Myeongdong (khu mua sắm), Myeongdong"},
{ko:"유명", vi:"Nổi tiếng, Famous"},
{ko:"전통", vi:"Truyền thống, Tradition"},
{ko:"항구", vi:"Cảng, Harbor"},
{ko:"구축", vi:"Xây dựng / thiết lập, Construction"},
{ko:"구축함", vi:"Tàu khu trục, Destroyer"},
{ko:"구축하다", vi:"Xây dựng / thiết lập, Build"},
{ko:"해상", vi:"Trên biển / hàng hải, Maritime"},
{ko:"가지 언어", vi:"Nhiều ngôn ngữ, Various languages"},
{ko:"결혼/ 결혼하다/ 결혼식", vi:"Marriage/Get married/Wedding"},
{ko:"경치/ 풍경", vi:"Phong cảnh, Landscape, Scenery"},
{ko:"경험/ 경험하다", vi:"Kinh nghiệm, Experience"},
{ko:"초등학생/ 초등학교", vi:"Elementary student/ Elementary school"},
{ko:"중학생/ 중학교", vi:"Middle school student/ Middle school"},
{ko:"고등학생/ 고등학교", vi:"High school student/ High school"},
{ko:"관광지", vi:"Điểm du lịch, Tourist attraction"},
{ko:"청와대", vi:"Nhà Xanh (Phủ Tổng thống Hàn Quốc), Blue House"},
{ko:"국립 민속 박물관", vi:"Bảo tàng Dân gian Quốc gia"},
{ko:"국립 중앙 박물관", vi:"Bảo tàng Quốc gia Trung ương"},
{ko:"국립 고궁 박물관", vi:"Bảo tàng Cung điện Quốc gia"},
{ko:"기념관", vi:"Nhà tưởng niệm, Memorial hall"},
{ko:"꼭대기", vi:"Đỉnh / trên cùng, Top"},
{ko:"닦다", vi:"Lau / chùi, Wipe"},
{ko:"동안", vi:"Trong suốt (khoảng thời gian), During"},
{ko:"되다", vi:"Trở thành, Become"},
{ko:"마을", vi:"Làng, Village"},
{ko:"마지막", vi:"Cuối cùng, Last"},
{ko:"막걸리", vi:"Rượu gạo Hàn Quốc, Makgeolli"},
{ko:"모습", vi:"Hình dáng / dáng vẻ, Appearance"},
{ko:"과정", vi:"Khóa học, Course"},
{ko:"수업/ 수업하다", vi:"Lớp học / buổi học, Class/ Dạy học / lên lớp, Teach"},
{ko:"안내하다", vi:"Hướng dẫn / thông báo, Guide / Inform"},
{ko:"오전/오후", vi:"Morning / Afternoon"},
{ko:"요일", vi:"Day of the week"},
{ko:"음료/ 음료수", vi:"Beverage, 음료 (trang trọng)/음료수 (đời thường)"},
{ko:"이번", vi:"Lần này, This time"},
{ko:"주간/ 야간/ 심야", vi:"Ban ngày / theo tuần, Daytime / Weekly/ Ban đêm, Nighttime/ Đêm khuya, Late night"},
{ko:"파티/ 파티하다", vi:"Bữa tiệc, Party/ Tổ chức, tham gia tiệc, Party"},
{ko:"회의", vi:"Cuộc họp, Meeting"},
{ko:"깨끗하다", vi:"Sạch sẽ, Clean"},
{ko:"근무/ 근무하다", vi:"a làm / trực, Duty / Work shift/Làm việc / trực, Be on duty"},
{ko:"기상/ 기상하다/ 일어나다", vi:"Thức dậy, Wake up"},
{ko:"체육", vi:"Thể dục, Physical education"},
{ko:"대회", vi:"Đại hội, Competition"},
{ko:"대화", vi:"Hội thoại, Conversation"},
{ko:"식사/ 식사하다", vi:"Meal/ Have a meal"},
{ko:"아내", vi:"Wife"},
{ko:"외식/ 외식하다", vi:"Eating out/ Eat out"},
{ko:"인터넷", vi:" Internet"},
{ko:"일과", vi:"Sinh hoạt hằng ngày / lịch làm việc, Daily routine"},
{ko:"정도", vi:"Mức độ, Degree / Extent"},
{ko:"일상생활", vi:"Sinh hoạt thường ngày, Daily life"},
  /* Từ loại */
{ko:"명사", vi:"Noun"},
{ko:"대명사", vi:"Đại từ, Pronoun"},
{ko:"수사", vi:"Số từ, Numeral"},
{ko:"동사", vi:"Verb"},
{ko:"형용사", vi:"Adjective"},
{ko:"부사", vi:"Trạng từ, Adverb"},
{ko:"관형사", vi:"Định từ, Determiner"},
{ko:"조사", vi:"Trợ từ, Particle"},
  /* Danh từ */
{ko:"안내", vi:"Hướng dẫn / thông báo, Guidance / Notice"},
{ko:"보고서", vi:"Report"},
{ko:"올림", vi:"Kính gửi / trân trọng (kết thư), Respectfully (closing)"},
{ko:"높임말", vi:"Kính ngữ, Honorific language"},
{ko:"평일", vi:"Ngày trong tuần, Weekday"},
{ko:"교육", vi:"Giáo dục / đào tạo, Education / Training"},
{ko:"원장", vi:"Viện trưởng / hiệu trưởng (học viện), Director"},
{ko:"중요하다", vi:"Quan trọng, Important"},
{ko:"행사/ 행사하다", vi:"Sự kiện, Event/Tổ chức sự kiện, Hold an event"},
{ko:"훈련/ 훈련하다", vi:"Training/ To train"},
{ko:"사격/ 사격하다/ 사격장", vi:"Shooting/ To shoot/ Trường bắn, Shooting range"},
{ko:"위병/ 위병소", vi:"Lính gác, Guard/Trạm gác, Guard post"},
{ko:"주변", vi:"Xung quanh, Surroundings"},
{ko:"출구/ 입구/ 출입구", vi:" Lối ra, Exit/ Lối vào, Entrance/ Lối ra vào, Entrance/Exit"},
{ko:"입교/ 입교하다/ 제대/ 제대하다", vi:"Nhập học (vào trường/khóa huấn luyện), Enrollment / Admission / Xuất ngũ, Discharge"},
{ko:"동료", vi:"Đồng nghiệp"},
{ko:"머리", vi:"Head / Hair"},
{ko:"아침/ 점심/저녁", vi:"Morning, Breakfast/ afternoon, Lunch/Everning, Dinner"},
{ko:"식료품", vi:"Groceries"},
{ko:"신문", vi:"Newspaper"},
{ko:"편지", vi:"Letter"},
{ko:"구경", vi:"Tham quan / xem, Sightseeing"},
{ko:"자르다", vi:"Cut"},
{ko:"훈련", vi:"Training"},
{ko:"배우다", vi:"Learn"},
{ko:"가르치다", vi:"Teach"},
{ko:"끝나다", vi:"End"},
{ko:"기간", vi:"Thời gian / thời hạn, Period"},
{ko:"문화", vi:"Culture"},
{ko:"연세", vi:"Tuổi (kính ngữ), Age (honorific)"},
{ko:"항상", vi:"Always"},
{ko:"다음주", vi:"Next week"},
{ko:"매주", vi:"Every week"},
{ko:"기념일", vi:"Ngày kỷ niệm, Anniversary"},
{ko:"몇", vi:"Mấy / bao nhiêu, How many"},
{ko:"날씨", vi:"Thời tiết, Weather"},
{ko:"값", vi:"Giá tiền, Price"},
{ko:"전기/ 전자", vi:"Điện, Electricity/ Điện tử, Electronic"},
{ko:"복사기", vi:"Máy photocopy, Copier"},
{ko:"쿠키", vi:"Bánh quy / cookie, Cookie"},
{ko:"언덕", vi:"Đồi, Hill"},
{ko:"도", vi:"Tỉnh/ Cũng/ Độ, Province/ Too/ Degree"},
{ko:"시", vi:"Thành phố, City"},
{ko:"군", vi:"Huyện (đơn vị hành chính), County"},
{ko:"읍", vi:"Thị trấn, Town"},
{ko:"면", vi:"Xã (đơn vị hành chính), Township"},
{ko:"동", vi:"Phường/khu phố/toà nhà, Neighborhood"},
{ko:"리", vi:"Làng (đơn vị hành chính nhỏ), Village unit"},  
{ko:"목소리", vi:"Giọng nói, Voice"},
{ko:"말하기/ 말하다", vi:"Kỹ năng nói/ Nói, Speaking"},
{ko:"박수", vi:"Vỗ tay, Applause, 박수를 치다 → vỗ tay. 박수를 받다 → được vỗ tay (được hoan nghênh). 박수를 보내다 → gửi tràng pháo tay"},
{ko:"물품/ 물건", vi:"Vật phẩm / hàng hóa 물품(trang trọng), 물건(đời thường), Goods"},
{ko:"아까", vi:"Lúc nãy, A while ago"}, 
{ko:"정답/ 오답", vi:"Đáp án đúng, Correct answer/ Đáp án sai"},
{ko:"예문", vi:"Câu ví dụ, Example sentence"},
{ko:"의미", vi:"Ý nghĩa, Meaning"}, 
{ko:"그러면", vi:"Vậy thì / nếu vậy thì, Then"},
{ko:"는데/ 지만", vi:"Nhưng / tuy nhiên (liên kết câu), But / Though"},
  /* Quân đội & Cấp bậc */
{ko:"분대", vi:"Tiểu đội, Squad"},
{ko:"소대/ 소대장/ 소대원", vi:"Trung đội, Platoon/ Trung đội trưởng, Platoon leader/ Thành viên trung đội, Platoon member"},
{ko:"중대", vi:"Đại đội, Company"},
{ko:"대대", vi:"Tiểu đoàn, Battalion"},
{ko:"연대", vi:"Trung đoàn, Regiment"},
{ko:"여단", vi:"Lữ đoàn, Brigade"},
{ko:"사단", vi:"Sư đoàn, Division"},
{ko:"군단", vi:"Quân đoàn, Corps"},
{ko:"군구", vi:"Quân khu, Military district"},
{ko:"군", vi:"Quân đội, Military"},
{ko:"국방부", vi:"Bộ Quốc phòng, Ministry of National Defense"},
{ko:"계급", vi:"Cấp bậc, Rank"},
{ko:"군종", vi:"Quân chủng, Military branch"},
{ko:"생도/ 장교", vi:"Cadet/ Officer"},
{ko:"장군", vi:"Tướng, General"},
{ko:"대장", vi:"Đại tướng, General of the army"},
{ko:"중장", vi:"Trung tướng, Lieutenant general"},
{ko:"소장", vi:"Thiếu tướng, Major general"},
{ko:"준장", vi:"Chuẩn tướng, Brigadier general"},
{ko:"대령", vi:"Đại tá, Colonel"},
{ko:"중령", vi:"Trung tá, Lieutenant colonel"},
{ko:"소령", vi:"Thiếu tá, Major"},
{ko:"대위", vi:"Đại úy, Captain"},
{ko:"중위", vi:"Trung úy, First lieutenant"},
{ko:"소위", vi:"Thiếu úy, Second lieutenant"},
{ko:"준위", vi:"Chuẩn úy, Warrant officer"},
{ko:"하사-중사-상사-원사", vi:"Hạ sĩ quan"},
{ko:"이병-일병-상병-병장", vi:"Binh nhì-Binh nhất-...."},
{ko:"부대", vi:"Đơn vị, Unit"},
{ko:"부대원", vi:"Quân nhân trong đơn vị, Unit member"},
{ko:"지휘관 명칭", vi:"Tên gọi chức vụ chỉ huy, Command title"},
{ko:"명령", vi:"Mệnh lệnh, Order"},
{ko:"경례", vi:"Chào (quân đội), Salute"},
{ko:"경례 구호", vi:"Khẩu lệnh chào, Salute command"},
{ko:"숙소", vi:"Nơi ở, Barracks"},
{ko:"군용품", vi:"Trang bị quân dụng, Military equipment"},
{ko:"군복", vi:"Quân phục, Military uniform"},
{ko:"군장", vi:"Quân trang, Military gear"},
{ko:"근무모/ 근무복/ 근무화", vi:"Mũ công vụ, Duty cap/Quân phục công vụ, Duty uniform/Giày công vụ, Duty shoes"},
{ko:"전투모/ 전투복/ 전투화", vi:"Mũ chiến đấu, Combat helmet/Quân phục chiến đấu, Combat uniform/Giày chiến đấu, Combat boots"},
{ko:"의무대", vi:"Quân y, Medical unit"},
 /* Vũ khí */ 
{ko:"무기", vi:"Weapon"},
{ko:"장갑차", vi:"Xe bọc thép, Armored vehicle"},
{ko:"자주포", vi:"Pháo tự hành, Self-propelled artillery"},
{ko:"포", vi:"Pháo, Cannon"},
{ko:"폭탄", vi:"Bomb"},
{ko:"견인포", vi:"Pháo kéo, Towed artillery"},
{ko:"박격포", vi:"Súng cối, Mortar"},
{ko:"기자", vi:"Nhà báo/Phóng viên, Reporter"},
{ko:"군인", vi:"Soldier"},
{ko:"의사", vi:"Doctor"},
{ko:"간호사", vi:"Nurse"},
{ko:"경찰/ 경찰관", vi:"Police/ Police officer"},
{ko:"변호사", vi:"Lawyer"},
{ko:"학생", vi:"Học sinh, sinh viên, Student"},
{ko:"가수", vi:"Ca sĩ, Singer"},
{ko:"배우", vi:"Diễn viên, Actor"},
{ko:"요리사/ 주방장", vi:"Đầu bếp/ Bếp trưởng, Chef"},
{ko:"농부", vi:"Nông dân, Farmer"},
{ko:"운전사", vi:"Tài xế, Driver"},
{ko:"조종사", vi:"Phi công, Pilot"},
{ko:"기술자", vi:"Kỹ thuật viên, Technician"},
{ko:"회사원", vi:"Nhân viên công ty, Office worker"},
{ko:"주부", vi:"Nội trợ, Housewife"},
{ko:"관리자", vi:"Quản lý, Manager"},
{ko:"주무관님", vi:"Quản lý chính"},
{ko:"부모님", vi:"Bố mẹ (kính ngữ), Parents"},
{ko:"아버지", vi:"Bố, cha, Father"},
{ko:"어머니", vi:"Mẹ, Mother"},
{ko:"엄마", vi:"Mẹ (thân mật), Mom"},
{ko:"오빠", vi:"Anh trai (nữ gọi), Older brother"},
{ko:"누나", vi:"Chị gái (nam gọi), Older sister"},
{ko:"언니", vi:"Chị gái (nữ gọi), Older sister (female speaker)"},
{ko:"동생", vi:"Em, Younger sibling"},
{ko:"삼촌", vi:"Chú, bác trai, Uncle"},
{ko:"이모", vi:"Dì, Aunt"},
{ko:"호칭", vi:"Cách xưng hô, Form of address"},
{ko:"씨", vi:"Hậu tố xưng hô lịch sự, Polite suffix"},
{ko:"자기", vi:"Bản thân / anh-em (thân mật), Honey / Self"},
{ko:"내", vi:"Của tôi / tôi (dạng bổ nghĩa), My"},
{ko:"아들/ 딸", vi:"Son/Daughter"},
{ko:"손님/ 승객", vi:"Khách, Guest/Hành khách, Passenger"},
{ko:"한국인", vi:"Người Hàn Quốc, Korean"},
{ko:"아이", vi:"Trẻ em, Child"},
{ko:"남자/여자", vi:"Nam giới, Man/Nữ giới, Woman"},
{ko:"국립", vi:"Quốc lập, National"},
{ko:"국가", vi:"Quốc gia, Nation"},
{ko:"애국가", vi:"Quốc ca, Nation"},
{ko:"국적", vi:"Quốc tịch, Nationality"},
{ko:"고향", vi:"Quê hương, Hometown"},
{ko:"도시", vi:"Thành phố, City"},
{ko:"동네", vi:"Khu phố / khu dân cư, Neighborhood"},
{ko:"장소", vi:"Địa điểm, Place"},
{ko:"공원", vi:"Công viên, Park"},
{ko:"학교", vi:"Trường học, School"},
{ko:"대학교", vi:"Trường đại học, University"},
{ko:"대학", vi:"Đại học, College"},
{ko:"교실", vi:"Phòng học, Classroom"},
{ko:"체력 단련실", vi:"Phòng tập thể lực, Gym"},
{ko:"연병장", vi:"Sân tập quân sự, Parade ground"},
{ko:"도서관", vi:"Library"},
{ko:"서점", vi:"Bookstore"},
{ko:"미술관", vi:"Bảo tàng mỹ thuật, Art museum"},
{ko:"극장", vi:"Rạp hát / rạp chiếu phim, Theater / Cinema"},
{ko:"병원", vi:"Hospital"},
{ko:"약국", vi:"Pharmacy"},
{ko:"은행", vi:"Bank"},
{ko:"우체국", vi:"Post office"},
{ko:"대사관", vi:"Đại sứ quán, Embassy"},
{ko:"백화점", vi:"Trung tâm thương mại, Department store"},
{ko:"시장", vi:"Chợ, Market"},
{ko:"슈퍼마켓", vi:"Supermarket"},
{ko:"매점", vi:"Cửa hàng nhỏ / căng tin, Convenience store"},
{ko:"미용실", vi:"Hair salon"},
{ko:"이발소", vi:"Barbershop"},
{ko:"호텔", vi:"Hotel"},
{ko:"사무소/ 사무실", vi:"Văn phòng (hành chính)/Văn phòng, Office"},
{ko:"주차장", vi:"Bãi đỗ xe, Parking lot"},
{ko:"화장실", vi:"Nhà vệ sinh, Restroom"},
{ko:"커피/ 커피숍", vi:"Cà phê, Coffee/Quán cà phê, Coffee shop"},
{ko:"본관", vi:"Tòa nhà chính, Main building"},
{ko:"생활관", vi:"Khu sinh hoạt / doanh trại, Living quarters"},
{ko:"버스", vi:"Bus"},
{ko:"택시", vi:"Taxi"},
{ko:"지하철", vi:"Tàu điện ngầm, Subway"},
{ko:"전철", vi:"Tàu điện trên mặt đất"},
{ko:"자전거", vi:"Xe đạp, Bicycle"},
{ko:"지하철역", vi:"Ga tàu điện ngầm, Subway station"},
{ko:"정류장", vi:"Stop"},
{ko:"요금소", vi:"Trạm thu phí, Toll booth"},
{ko:"승차/ 하차", vi:"Lên xe, Boarding/Xuống xe, Getting off"},
{ko:"출발", vi:"Xuất phát, Departure"},
{ko:"도착", vi:"Đến nơi, Arrival"},
{ko:"운전면허증", vi:"Driver’s license"},
{ko:"냉장고/ 냉동실/ 냉장실", vi:"Refrigerator/ Freezer compartment/ Refrigerator compartment"},
{ko:"선풍기", vi:"Quạt điện, Electric fan"},
{ko:"다리미", vi:"Bàn ủi, Iron"},
{ko:"전화/ 휴대폰/ 핸드폰/ 스마트폰", vi:"Điện thoại, Mobile phone"},
{ko:"컴퓨터", vi:"Computer"},
{ko:"텔레비전", vi:"Television"},
{ko:"라디오", vi:"Radio"},
{ko:"카메라/ 사진기", vi:"Camera"},
{ko:"부엌용품", vi:"Đồ dùng nhà bếp, Kitchen utensils"},
{ko:"그릇/ 접시", vi:"Bowl/ Plate"},
{ko:"냄비", vi:"Nồi, Pot"},
{ko:"전기밥솥", vi:"Nồi cơm điện, Rice cooker"},
{ko:"프라이팬", vi:"Chảo chiên, Frying pan"},
{ko:"젓가락/ 숟가락/ 포크", vi:"Chopsticks/ Spoon/ Fork"},
{ko:"컵", vi:"Cốc, Cup"},
{ko:"비누", vi:"Xà phòng, Soap"},
{ko:"세탁기/ 세탁 비누/ 세탁 세제", vi:"Washing machine/ Xà phòng giặt, Laundry soap/ Bột/nước giặt, Laundry detergent"},
{ko:"주방 세제", vi:"Nước rửa chén, Dishwashing detergent"},
{ko:"샴푸", vi:"Shampoo"},
{ko:"치약/ 칫솔", vi:"Toothpaste/ Toothbrush"},
{ko:"면도기", vi:"Razor"},
{ko:"휴지", vi:"Toilet paper"},
{ko:"물티슈", vi:" Wet wipes"},
{ko:"수건", vi:"Towel"},
{ko:"거울", vi:"Mirror"},
{ko:"향", vi:"Hương, nhang/ Mùi hương / hương thơm, Scent / Aroma"},
{ko:"쓰레기/ 빗자루/ 쓰레받기/ 쓰레기통/ 쓰레장", vi:"Rác, Chổi/Broom, Hót rác/Dustpan, Thùng rác/Trash can, Bãi rác"},
{ko:"옷/ 옷장", vi:"Quần áo, Clothes/ Tủ quần áo, Wardrobe"},
{ko:"바지", vi:"Quần, Pants"},
{ko:"치마", vi:"Váy, Skirt"},
{ko:"스웨터", vi:"Áo len, Sweater"},
{ko:"모자", vi:"Mũ, Hat"},
{ko:"장갑", vi:"Găng tay, Gloves"},
{ko:"구두", vi:"Giày da, Dress shoes"},
{ko:"슬리퍼", vi:"Dép lê, Slippers"},
{ko:"안경", vi:"Kính, Glasses"},
{ko:"선글라스", vi:"Kính râm, Sunglasses"},
{ko:"가방", vi:"Bag"},
{ko:"지갑", vi:"Wallet"},
{ko:"여권", vi:"Passport"},
{ko:"열쇠", vi:"Key"},
{ko:"사물함", vi:"Tủ cá nhân, Locker"},
{ko:"소파", vi:"Sofa"},
{ko:"침대", vi:"Bed"},
{ko:"책상", vi:"Bàn học/làm việc, Desk"},
{ko:"의자", vi:"Chair"},
{ko:"탁자", vi:"Table"},
{ko:"기구", vi:"Dụng cụ / thiết bị, Equipment"},
{ko:"사진", vi:"Photo"},
{ko:"밥", vi:"Rice"},
{ko:"볶음밥", vi:"Fried rice"},
{ko:"라면", vi:"Mì ăn liền, Instant noodles"},
{ko:"국수", vi:"Noodles"},
{ko:"샌드위치", vi:"Bánh mì kẹp, Sandwich"},
{ko:"햄버거", vi:"Hamburger"},
{ko:"파스타", vi:"Mì Ý, Pasta"},
{ko:"김밥", vi:"Cơm cuộn rong biển, Gimbap"},
{ko:"비빔밥", vi:"Bibimbap"},
{ko:"죽", vi:"Cháo, Porridge"},
{ko:"떡", vi:"Bánh gạo, Rice cake"},
{ko:"빵", vi:"Bread"},
{ko:"피자", vi:"Pizza"},
{ko:"치킨", vi:"Fried chicken"},
{ko:"불고기", vi:"Thịt nướng"},
{ko:"삼겹살", vi:"Thịt ba chỉ, Pork belly"},
{ko:"소고기", vi:"Beef"},
{ko:"돼지고기", vi:"Thịt heo, Pork"},
{ko:"닭고기", vi:"Chicken"},
{ko:"계란", vi:"Egg"},
{ko:"달걀", vi:"Egg"},
{ko:"버터", vi:"Butter"},
{ko:"채소", vi:"Vegetables"},
{ko:"샐러드", vi:"Salad, Salad"},
{ko:"국", vi:"Soup"},
{ko:"찌개", vi:"Canh hầm, Stew"},
{ko:"반찬", vi:"Món ăn kèm, Side dish"},
{ko:"삼계탕", vi:"Canh gà hầm sâm, Ginseng chicken soup"},
{ko:"고기", vi:"Thịt, Meat"},
{ko:"생선/ 물고기/ 회", vi:"Cá (món ăn)/ Cá sống (không ăn)/ Cá sống (ẩm thực Hàn), Sashimi"},
{ko:"굴", vi:"Hàu, Oyster"},
{ko:"민물고기", vi:"Cá nước ngọt/ Freshwater fish"},
{ko:"고등어", vi:"Cá thu, Mackerel"},
{ko:"참치", vi:"Cá ngừ, Tuna"},
{ko:"연어", vi:"Cá hồi, Salmon"},
{ko:"새우", vi:"Shrimp"},
{ko:"게", vi:"Crab"},
{ko:"오징어", vi:"Mực ống, Squid"},
{ko:"문어", vi:"Bạch tuộc, Octopus"},
{ko:"미역", vi:"Rong biển, Seaweed"},
{ko:"과일", vi:"Fruit"},
{ko:"키위", vi:"Kiwi"},
{ko:"사과", vi:"Apple"},
{ko:"포도", vi:"Grape"},
{ko:"딸기", vi:"Strawberry"},
{ko:"바나나", vi:"Banana"},
{ko:"레몬", vi:"Lemon"},
{ko:"수박", vi:"Watermelon"},
{ko:"오렌지", vi:"Orange"},
{ko:"망고", vi:"Mango"},
{ko:"복숭아", vi:"Peach"},
{ko:"체리", vi:"Cherry"},
{ko:"양념", vi:"Gia vị đã pha/ đồ nêm, Seasoning"},
{ko:"조미료", vi:"Gia vị (chất điều vị), Seasoning / Condiment"},
{ko:"당근", vi:"Carrot"},
{ko:"감자", vi:"Potato"},
{ko:"오이", vi:"Cucumber"},
{ko:"양배추", vi:"Cabbage"},
{ko:"파", vi:"Green onion"},
{ko:"고추", vi:"Chili pepper"},
{ko:"토마토", vi:"Tomato"},
{ko:"상추", vi:"Xà lách, Lettuce"},
{ko:"배추", vi:"Cải thảo, Napa cabbage"},
{ko:"브로콜리", vi:"Broccoli"},
{ko:"가지", vi:"Cà tím, Eggplant"},
{ko:"콩", vi:"Bean"},
{ko:"버섯", vi:"Mushroom"},
{ko:"후추", vi:"Pepper"},
{ko:"소금", vi:"Salt"},
{ko:"설탕", vi:"Sugar"},
{ko:"꿀", vi:"Honey"},
{ko:"땅콩", vi:"Đậu phộng, Peanut"},
{ko:"간장", vi:"Nước tương, Soy sauce"},
{ko:"고추장", vi:"Tương ớt Hàn Quốc, Chilli sauce"},
{ko:"된장", vi:"Tương đậu nành, Soybean paste"},
{ko:"마늘", vi:"Garlic"},
{ko:"양파", vi:"Onion"},
{ko:"식초", vi:"Giấm, Vinegar"},
{ko:"기름", vi:"Oil"},
{ko:"케이크", vi:"Cake"},
{ko:"초콜릿", vi:"Chocolate"},
{ko:"아이스크림", vi:"Ice cream"},
{ko:"시리얼", vi:"Ngũ cốc, Cereal"},
{ko:"물", vi:"Water"},
{ko:"차", vi:"Car, Tea"},
{ko:"술", vi:"Rượu, Alcohol"},
{ko:"맥주", vi:"Bia, Beer"},
{ko:"우유", vi:"Sữa, Milk"},
{ko:"두유", vi:"Sữa đậu nành, Soy milk"},
{ko:"콜라", vi:"Coca, Cola"},
{ko:"녹차", vi:"Trà xanh, Green tea"},
{ko:"홍차", vi:"Hồng trà, Black tea"},
{ko:"와인", vi:"Rượu vang, Wine"},
{ko:"하루", vi:"Một ngày, One day"},
{ko:"낮", vi:"Ban ngày, Daytime"},
{ko:"밤", vi:"Ban đêm, Night"},
{ko:"매일", vi:"Every day"},
{ko:"요즘", vi:"Dạo này, These days"},
{ko:"주말", vi:"Weekend"},
{ko:"방학", vi:"Kỳ nghỉ (của học sinh, sinh viên), School vacation"},
{ko:"방학하다", vi:"Nghỉ học (kỳ nghỉ), Be on vacation"},
{ko:"휴가", vi:"Kỳ nghỉ / nghỉ phép, Vacation"},
{ko:"일정", vi:"Schedule"},
{ko:"전", vi:"Before"},
{ko:"후", vi:"After"},
{ko:"때", vi:"When"},
{ko:"시간", vi:"Thời gian / giờ, Time"},
{ko:"분", vi:"Vị, ngài(người), Phút, Minute"},
{ko:"월요일", vi:"Monday"},
{ko:"화요일", vi:"Tuesday"},
{ko:"수요일", vi:"Wednesday"},
{ko:"목요일", vi:"Thursday"},
{ko:"금요일", vi:"Friday"},
{ko:"토요일", vi:"Saturday"},
{ko:"일요일", vi:"Sunday"},
{ko:"봄", vi:"Spring"},
{ko:"여름", vi:"Summer"},
{ko:"가을", vi:"Autumn"},
{ko:"겨울", vi:"Winter"},
{ko:"수", vi:"Number"},
{ko:"단위", vi:"Đơn vị, Unit"},
{ko:"큰 수", vi:"Large number"},
{ko:"번호", vi:"Số thứ tự / số hiệu, Number"},
{ko:"요금", vi:"Fee"},
{ko:"요금표", vi:"Bảng giá, Price list"},
{ko:"돈", vi:"Money"},
{ko:"화폐", vi:"Tiền tệ, Currency"},
  /* Danh từ màu sắc */
{ko:"흰색", vi:"Màu trắng, White color"},
{ko:"검은색/검정색", vi:"Màu đen, Black color"},
{ko:"빨간색", vi:"Màu đỏ, Red color"},
{ko:"파란색", vi:"Màu xanh dương (xanh nước biển), Blue color"},
{ko:"노란색", vi:"Màu vàng, Yellow color"},
{ko:"초록색", vi:"Màu xanh lá, Green color"},
{ko:"주황색", vi:"Màu cam, Orange color"},
{ko:"보라색", vi:"Màu tím, Purple color"},
{ko:"분홍색", vi:"Màu hồng, Pink color"},
{ko:"갈색", vi:"Màu nâu, Brown color"},
{ko:"회색", vi:"Màu xám, Gray color"},
{ko:"하늘색", vi:"Màu xanh da trời nhạt, Sky blue"},
{ko:"남색", vi:"Màu xanh đậm (xanh hải quân), Navy blue"},
{ko:"금색", vi:"Màu vàng kim, Gold color"},
{ko:"은색", vi:"Màu bạc, Silver color"},
  /* Hoạt động – Thể thao – Giải trí */
  /* Thể thao */
{ko:"산책/ 산책하다", vi:"Đi dạo, Walk"},
{ko:"수영/ 수영하다/ 수영장", vi:"Swimm/ Swimming"},
{ko:"댄스", vi:"Nhảy, Dance"},
{ko:"등산/ 등산하다", vi:"Leo núi, Hiking"},
{ko:"쇼핑/ 쇼핑하다/ 쇼핑센터", vi:"Shop/ Tp Shop/ Shopping center"},
{ko:"축구/축구화", vi:"Bóng đá, Soccer/ Giày bóng đá"},
{ko:"농구", vi:"Bóng rổ, Basketball"},
{ko:"배구", vi:"Bóng chuyền, Volleyball"},
{ko:"테니스", vi:"Quần vợt, Tennis"},
{ko:"배드민턴", vi:"Cầu lông, Badminton"},
{ko:"요가", vi:"Yoga, Yoga"},
{ko:"게임하다", vi:"Chơi game, Play games"},
{ko:"영화보다", vi:"Xem phim, Watch a movie"},
{ko:"사진 찍다", vi:"Chụp ảnh, Take photos"},
  /* Học tập & Ngôn ngữ */
{ko:"복습", vi:"Ôn tập, Review"},
{ko:"완성하다", vi:"Hoàn thành, To complete"},
{ko:"발표하다", vi:"Trình bày, To present"},
{ko:"표현", vi:"Biểu đạt, Expression"},
{ko:"문장", vi:"Câu văn, Sentence"},
{ko:"한글", vi:"Chữ Hàn, Hangul"},
{ko:"모음", vi:"Nguyên âm, Vowel"},
{ko:"자음", vi:"Phụ âm, Consonant"},
{ko:"받침", vi:"Phụ âm cuối, Final consonant"},
{ko:"문법", vi:"Ngữ pháp, Grammar"},
{ko:"어휘", vi:"Từ vựng, Vocabulary"},
{ko:"단원", vi:"Bài học / đơn vị bài, Unit"},
{ko:"주제", vi:"Chủ đề, Topic"},
{ko:"학습", vi:"Học tập, Learning"},
{ko:"활동", vi:"Hoạt động, Activity"},
{ko:"교재", vi:"Giáo trình, Textbook"},
{ko:"본문", vi:"Nội dung chính (bài đọc), Main text"},
{ko:"글", vi:"Bài viết / văn bản, Text"},
{ko:"구성/구성하다", vi:"Cấu trúc, Structure/ Cấu thành, sắp xếp, Organize"},
{ko:"소개", vi:"Giới thiệu, Introduction"},
{ko:"숙제", vi:"Bài tập về nhà, Homework"},
{ko:"연습", vi:"Luyện tập, Practice"},
/* Thông tin & Giao tiếp */
{ko:"상황", vi:"Tình huống, Situation"},
{ko:"정보", vi:"Thông tin, Information"},
{ko:"공지", vi:"Thông báo, Notice"},
{ko:"공지 사항", vi:"Thông báo (chung), Announcement"},
{ko:"이메일", vi:"Email, Email"},
{ko:"약속", vi:"Cuộc hẹn / lời hứa, Appointment / Promise"},
{ko:"관련", vi:"Liên quan, Related"},
{ko:"대답", vi:"Câu trả lời, Answer"},
{ko:"주소", vi:"Địa chỉ, Address"},
{ko:"연결하다", vi:"Kết nối, Connect"},
  /* Đồ dùng học tập */
{ko:"종이", vi:"Giấy, Paper"},
{ko:"필통", vi:"Hộp bút, Pencil case"},
{ko:"연필", vi:"Bút chì, Pencil"},
{ko:"볼펜", vi:"Bút bi, Ballpoint pen"},
{ko:"지우개", vi:"Cục tẩy, Eraser"},
{ko:"공책", vi:"Vở, Notebook"},
{ko:"자", vi:"Thước kẻ, Ruler"},
{ko:"가위", vi:"Kéo, Scissors"},
{ko:"사전", vi:"Từ điển, Dictionary"},
  /* Khác */
{ko:"가짜", vi:"Fake"},
{ko:"꿈", vi:"Dream"},
{ko:"실수", vi:"Sơ suất, Mistake"},
{ko:"잘못", vi:"Lỗi / điều sai, Fault"}, 
  /* Thiên nhiên */
{ko:"별", vi:"Star"},
{ko:"나무", vi:"Tree"},
{ko:"하늘", vi:"Bầu trời, Sky"},
{ko:"구름", vi:"Cloud"},
{ko:"해, 태양", vi:"Sun"},
{ko:"비", vi:"Rain"},
{ko:"눈", vi:"Eye/Snow"},
{ko:"바람", vi:"Wind"},
{ko:"산", vi:"Mountain"},
{ko:"강", vi:"River"},
{ko:"바다", vi:"Sea"},
{ko:"숲", vi:"Forest"},
  /* Động vật */
{ko:"고래", vi:"Whale"},
{ko:"코끼리", vi:"Elephant"},
{ko:"거미", vi:"Spider"},
{ko:"강아지", vi:"Chó con, Puppy"},
{ko:"고양이", vi:"Cat"},
{ko:"새", vi:"New/Bird"},
{ko:"말", vi:"Horse"},
{ko:"소", vi:"Cow"},
{ko:"돼지", vi:"Pig"},
{ko:"닭", vi:"Chicken"},
/* Vị trí */
{ko:"위치", vi:"Position"},
{ko:"층", vi:"Floor"},
{ko:"밑", vi:"Under"},
{ko:"옆", vi:"Next to"},
{ko:"맞은편", vi:"Opposite"},
{ko:"건너편", vi:"Bên kia / đối diện, Across / Opposite"},
{ko:"위", vi:"Above"},
{ko:"아래", vi:"Below"},
{ko:"앞", vi:"Front"},
{ko:"뒤", vi:"Back"},
{ko:"안", vi:"Inside"},
{ko:"밖", vi:"Outside"},
{ko:"가운데", vi:"Middle"},
{ko:"한강", vi:"Han River"},
{ko:"건물", vi:"Building"},
{ko:"근처", vi:"Gần đây / khu vực gần, Nearby"},
/* Phương hướng */
{ko:"방향", vi:"Hướng, Direction"},
{ko:"왼쪽, 좌측", vi:"Left"},
{ko:"오른쪽, 우측", vi:"Right"},
/* Động từ */
{ko:"가다", vi:"Go"},
{ko:"타다", vi:"Lên (xe), Ride"},
{ko:"운전하다", vi:"Lái xe, Drive"},
{ko:"조종하다", vi:"Điều khiển, Control"},
{ko:"걷다", vi:"Đi bộ, Walk"},
{ko:"뛰기/ 뛰다", vi:"Chạy, nhảy (bộc phát), Run"},
{ko:"달리기/ 달리다", vi:"Chạy (liên tục), Run"},
{ko:"건너다", vi:"Cross"},
{ko:"들어가다", vi:"Đi vào, Enter"},
{ko:"돌아가다", vi:"Return"},
{ko:"이동하다", vi:"Move"},
{ko:"출발하다", vi:"Khởi hành, Depart"},
{ko:"도착하다", vi:"Arrive"},
{ko:"지나가다", vi:"Đi ngang qua, Pass by"},
{ko:"마시다", vi:"Drink"},
{ko:"쉬다", vi:"Rest"},
{ko:"목욕하다", vi:"Take a bath"},
{ko:"샤워하다", vi:"Take a shower"},
{ko:"청소하다", vi:"Clean"},
{ko:"요리하다", vi:"Cook"},
{ko:"설거지하다", vi:"Rửa bát, Wash dishes"},
{ko:"빨래하다", vi:"Giặt đồ, Do laundry"},
{ko:"다림질하다", vi:"Là ủi, Iron clothes"},
{ko:"세수하다", vi:"Rửa mặt, Wash face"},
{ko:"양치하다", vi:"Đánh răng, Brush teeth"},
{ko:"화장하다", vi:"Trang điểm, Put on makeup"},
{ko:"옷을 입다", vi:"Mặc quần áo, Get dressed"},
{ko:"옷을 벗다", vi:"Cởi quần áo, Take off clothes"},
{ko:"고장나다", vi:"Bị hỏng, Break down"},
{ko:"끄다", vi:"Turn off"},
{ko:"켜다", vi:"Turn on"},
{ko:"반하다", vi:"Phải lòng / bị cuốn hút, Fall for, 그녀에게 반했어요. Tôi đã phải lòng cô ấy"},
{ko:"팔로우", vi:"Follow"},
{ko:"플러팅", vi:"Tán tỉnh, Flirting"},
{ko:"사다/ 구매하다", vi:"Buy/ Purchase"},
{ko:"일/ 일하다", vi:"Work"},
{ko:"공부/ 공부하다", vi:"Study"},
{ko:"준비/ 준비하다", vi:"Preparation/ Prepare"},
{ko:"시작/ 시작하다", vi:"Start"},
{ko:"표현하다", vi:"Biểu đạt, Express"},
{ko:"생각하다", vi:"Think"},
{ko:"이해하다", vi:"Understand"},
{ko:"알다", vi:"Know"},
{ko:"말하다", vi:"Speak"},
{ko:"이야기", vi:"Câu chuyện / nói chuyện, Story / Talk"},
{ko:"묻다", vi:"Ask"},
{ko:"대답하다", vi:"Trả lời, Answer"},
{ko:"답하다", vi:"Trả lời (trang trọng), Reply"},
{ko:"인사하다", vi:"Greet"},
{ko:"만나다", vi:"Meet"},
{ko:"확인하다", vi:"Xác nhận / kiểm tra, Confirm / Check"},
  /* Tính từ */
{ko:"짧다", vi:"Short"},
{ko:"길다", vi:"Long"},
{ko:"넓다", vi:"Wide"},
{ko:"좁다", vi:"Narrow"},
{ko:"높다", vi:"High"},
{ko:"낮다", vi:"Low"},
{ko:"무겁다", vi:"Heavy"},
{ko:"두껍다", vi:"Thick"},
{ko:"얇다", vi:"Thin"},
{ko:"차갑다", vi:"Cold"},
{ko:"뜨겁다", vi:"Hot"},
{ko:"느리다", vi:"Slow"},
{ko:"멋있다", vi:"Đẹp trai, Cool"},
{ko:"무섭다", vi:"Scary"},
{ko:"어렵다", vi:"Difficult"},
{ko:"쉽다", vi:"Easy"},
{ko:"밝다", vi:"Bright"},
{ko:"어둡다", vi:"Dark"},
{ko:"시끄럽다", vi:"Noisy"},
{ko:"조용하다", vi:"Quiet"},
{ko:"많다", vi:"Many"},
{ko:"적다", vi:"Few"},
{ko:"걱정하다", vi:"Worry"},
{ko:"잊어버리다", vi:"To forget"},
{ko:"잃어버리다", vi:"To lose"},
{ko:"실수하다", vi:"Mắc lỗi (vô ý), Make a mistake"},
{ko:"잘못하다", vi:"Do wrong"},
{ko:"대하다", vi:"Đối xử / đối diện, To treat / face"},
{ko:"같다", vi:"Same / Similar"},
{ko:"이상", vi:"Trở lên / bất thường, Above / Abnormal"},
  /* Tri giác */
{ko:"보다", vi:"See / Watch"},
{ko:"보이다", vi:"Được nhìn thấy, Be seen"},
{ko:"듣다", vi:"Listen"},
{ko:"읽다", vi:"Read"},
{ko:"쓰다", vi:"Write / Use"},
  /* Tính từ – Miêu tả */
{ko:"좋다", vi:"Good"},
{ko:"나쁘다", vi:"Bad"},
{ko:"크다", vi:"Big"},
{ko:"작다", vi:"Small"},
{ko:"없다", vi:"Not exist"},
{ko:"바쁘다", vi:"Busy"},
{ko:"즐겁다", vi:"Vui vẻ, Joyful"},
{ko:"기쁘다", vi:"Vui mừng, Glad"},
{ko:"심심하다", vi:"Bored"},
{ko:"화나다", vi:"Angry"},
{ko:"멀다", vi:"Far"},
{ko:"덥다", vi:"Hot"},
{ko:"아름답다", vi:"Beautiful"},
{ko:"맛있다", vi:"Delicious"},
{ko:"불편하다", vi:"Uncomfortable"},
{ko:"편하다", vi:"Comfortable"},
{ko:"귀엽다", vi:"Cute"},
  /* Biểu hiện & mức độ */
{ko:"어떻다", vi:"Như thế nào, How"},
{ko:"어떠하다", vi:"Như thế nào (trang trọng), How (formal)"},
{ko:"천천히 하다", vi:"Làm chậm rãi, Do slowly"},
 /* Trạng từ */
{ko:"아주/매우", vi:"Rất, Very"},
{ko:"그냥", vi:"Cứ / đơn giản là, Just"},
{ko:"그렇게", vi:"Như vậy, Like that"},
{ko:"같이", vi:"Together"},
{ko:"열심히", vi:"Chăm chỉ, Diligently"},
{ko:"많이", vi:"A lot"},
{ko:"빨리", vi:"Quickly"},
{ko:"천천히", vi:"Slowly"},
{ko:"자주", vi:"Thường xuyên, Often"},
{ko:"가끔", vi:"Thỉnh thoảng, Sometimes"},
{ko:"항상", vi:"Always"},
{ko:"벌써/이미", vi:"Đã.... rồi,벌써 한국에 온 지 1년이 됐어요. Mới đó mà đã 1 năm kể từ khi đến Hàn Quốc.벌써 다 끝났어요? Xong hết rồi à? (Nhanh vậy?). 이미 다 끝났어요. Đã xong hết rồi. (Báo sự thật)"},
{ko:"마음대로", vi:"Theo ý mình, As one pleases"},
{ko:"갑자기", vi:"Suddenly"},
{ko:"아마", vi:"Probably"},
{ko:"건기", vi:"Mùa khô, Dry season"},
{ko:"처럼", vi:"Như / giống như, Like / As"},
{ko:"편리", vi:"Sự tiện lợi, Convenience"},
{ko:"편리하다", vi:"Tiện lợi, Convenient"},
{ko:"부르다", vi:"Gọi / hát, Call / Sing"},
{ko:"회사 차량", vi:"Xe công ty, Company vehicle"},
{ko:"목걸이", vi:"Dây chuyền, Necklace"},
{ko:"목도리", vi:"Khăn quàng cổ, Scarf"},


{ko:"몸", vi:"Cơ thể, Body"},
{ko:"신체", vi:"Thân thể, Human body"},
{ko:"머리", vi:"Đầu, Head"},
{ko:"얼굴", vi:"Khuôn mặt, Face"},
{ko:"이마", vi:"Trán, Forehead"},
{ko:"눈", vi:"Mắt, Eye"},
{ko:"눈썹", vi:"Lông mày, Eyebrow"},
{ko:"속눈썹", vi:"Lông mi, Eyelash"},
{ko:"귀", vi:"Tai, Ear"},
{ko:"코", vi:"Mũi, Nose"},
{ko:"입", vi:"Miệng, Mouth"},
{ko:"입술", vi:"Môi, Lip"},
{ko:"이", vi:"Răng, Tooth"},
{ko:"혀", vi:"Lưỡi, Tongue"},
{ko:"턱", vi:"Cằm, Chin"},
{ko:"목", vi:"Cổ, Neck"},
{ko:"어깨", vi:"Vai, Shoulder"},
{ko:"팔", vi:"Cánh tay, Arm"},
{ko:"팔꿈치", vi:"Khuỷu tay, Elbow"},
{ko:"손", vi:"Bàn tay, Hand"},
{ko:"손가락", vi:"Ngón tay, Finger"},
{ko:"손톱", vi:"Móng tay, Fingernail"},
{ko:"가슴", vi:"Ngực, Chest"},
{ko:"배", vi:"Bụng, Belly / Abdomen"},
{ko:"허리", vi:"Eo / lưng dưới, Waist"},
{ko:"등", vi:"Lưng, Back"},
{ko:"엉덩이", vi:"Mông, Buttocks"},
{ko:"다리", vi:"Chân/ Cầu, Leg/ Bridge"},
{ko:"허벅지", vi:"Đùi, Thigh"},
{ko:"무릎", vi:"Đầu gối, Knee"},
{ko:"종아리", vi:"Bắp chân, Calf"},
{ko:"발", vi:"Bàn chân, Foot"},
{ko:"발가락", vi:"Ngón chân, Toe"},
{ko:"발목", vi:"Mắt cá chân, Ankle"},
{ko:"뼈", vi:"Xương, Bone"},
{ko:"근육", vi:"Cơ bắp, Muscle"},
{ko:"피", vi:"Máu, Blood"},
{ko:"심장", vi:"Tim, Heart"},
{ko:"폐", vi:"Phổi, Lung"},
{ko:"위", vi:"Dạ dày, Stomach"} 
];
