var WORDS = [

{ko:"정리", vi:"Sắp xếp / tổng hợp, Organization"},
{ko:"정리하다", vi:"Sắp xếp / dọn dẹp, Organize"},
{ko:"중식", vi:"Bữa trưa (phong cách Trung Hoa), Lunch / Chinese meal"},
{ko:"취침", vi:"Đi ngủ, Bedtime"},
{ko:"취침하다", vi:"Đi ngủ, Go to bed"},
{ko:"친절하다", vi:"Thân thiện, Kind"},
{ko:"혼자", vi:"Một mình, Alone"},
{ko:"휴식", vi:"Nghỉ ngơi, Rest"},
{ko:"휴식하다", vi:"Nghỉ ngơi, Take a rest"},
{ko:"세면", vi:"Rửa mặt, Washing up"},
{ko:"세면하다", vi:"Rửa mặt, Wash face"},
{ko:"현장 학습", vi:"Học tập thực tế, Field trip"},
{ko:"뜀걸음", vi:"Chạy nhẹ, Jogging"},
{ko:"뜀걸음하다", vi:"Chạy nhẹ, Jog"},
{ko:"점호", vi:"Điểm danh (quân đội), Roll call"},
{ko:"점호하다", vi:"Điểm danh, Call roll"},
{ko:"갈비", vi:"Sườn (bò/heo), Ribs"},
{ko:"갈비탕", vi:"Canh sườn bò, Beef rib soup"},
{ko:"계절", vi:"Mùa, Season"},
{ko:"괜찮다", vi:"Ổn / không sao, Okay"},
{ko:"기념품", vi:"Quà lưu niệm, Souvenir"},
{ko:"김치찌개", vi:"Canh kimchi, Kimchi stew"},
{ko:"낚시", vi:"Câu cá, Fishing"},
{ko:"낚시하다", vi:"Câu cá, Go fishing"},
{ko:"내년", vi:"Năm sau, Next year"},
{ko:"장년", vi:"Tuổi trung niên, Middle age"},
{ko:"작년", vi:"Năm ngoái, Last year"},
{ko:"올해", vi:"Năm nay, This year"},
{ko:"금년", vi:"Năm nay (trang trọng), This year (formal)"},
{ko:"냉면", vi:"Mì lạnh, Cold noodles"},
{ko:"녹색", vi:"Màu xanh lá, Green"},
{ko:"나뭇잎", vi:"Lá cây, Leaf"},
{ko:"다음", vi:"Tiếp theo, Next"},
{ko:"단풍", vi:"Lá đỏ mùa thu, Autumn leaves"},
{ko:"닫다", vi:"Đóng, Close"},
{ko:"열다", vi:"Mở, Open"},
{ko:"된장찌개", vi:"Canh tương đậu, Soybean paste stew"},
{ko:"인공", vi:"Nhân tạo, Artificial"},
{ko:"인조", vi:"Giả / nhân tạo, Synthetic"},
{ko:"인위", vi:"Nhân tạo / do con người tạo, Man-made"},
{ko:"색", vi:"Màu sắc, Color"},
{ko:"쇼핑센터", vi:"Trung tâm mua sắm, Shopping center"},
{ko:"스키", vi:"Trượt tuyết, Ski"},
{ko:"스키장", vi:"Khu trượt tuyết, Ski resort"},
{ko:"슬프다", vi:"Buồn, Sad"},
{ko:"죽다", vi:"Chết, Die"},
{ko:"아프다", vi:"Đau / bị bệnh, Sick"},
{ko:"역", vi:"Nhà ga, Station"},
{ko:"연락", vi:"Liên lạc, Contact"},
{ko:"연락하다", vi:"Liên lạc, Contact"},
{ko:"죄송하다", vi:"Xin lỗi (trang trọng), Sorry"},
{ko:"초대", vi:"Lời mời, Invitation"},
{ko:"초대하다", vi:"Mời, Invite"},
{ko:"출근", vi:"Đi làm, Go to work"},
{ko:"출근하다", vi:"Đi làm, Commute"},
{ko:"키", vi:"Chiều cao, Height"},
{ko:"탁구", vi:"Bóng bàn, Table tennis"},
{ko:"명동", vi:"Myeongdong (khu mua sắm), Myeongdong"},
{ko:"유명", vi:"Nổi tiếng, Famous"},
{ko:"전통", vi:"Truyền thống, Tradition"},
{ko:"항구", vi:"Cảng, Harbor"},
{ko:"구축", vi:"Xây dựng / thiết lập, Construction"},
{ko:"구축함", vi:"Tàu khu trục, Destroyer"},
{ko:"구축하다", vi:"Xây dựng / thiết lập, Build"},
{ko:"해상", vi:"Trên biển / hàng hải, Maritime"},
{ko:"가지 언어", vi:"Nhiều ngôn ngữ, Various languages"},
{ko:"결혼", vi:"Kết hôn, Marriage"},
{ko:"결혼하다", vi:"Kết hôn, Get married"},
{ko:"결혼식", vi:"Lễ cưới, Wedding"},
{ko:"경치", vi:"Phong cảnh, Scenery"},
{ko:"풍경", vi:"Cảnh vật, Landscape"},
{ko:"경험", vi:"Kinh nghiệm, Experience"},
{ko:"경험하다", vi:"Trải nghiệm, Experience"},
{ko:"고등학교", vi:"Trường cấp 3, High school"},
{ko:"고등학생", vi:"Học sinh cấp 3, High school student"},
{ko:"초등학교", vi:"Trường tiểu học, Elementary school"},
{ko:"초등학생", vi:"Học sinh tiểu học, Elementary student"},
{ko:"중학교", vi:"Trường cấp 2, Middle school"},
{ko:"중학생", vi:"Học sinh cấp 2, Middle school student"},
{ko:"관광지", vi:"Điểm du lịch, Tourist attraction"},
{ko:"청와대", vi:"Nhà Xanh (Phủ Tổng thống Hàn Quốc), Blue House"},
{ko:"국립", vi:"Quốc lập, National"},
{ko:"민속", vi:"Dân gian, Folk"},
{ko:"고궁", vi:"Cung điện cổ, Royal palace"},
{ko:"박물관", vi:"Bảo tàng, Museum"},
{ko:"기념관", vi:"Nhà kỷ niệm, Memorial hall"},
{ko:"꼭대기", vi:"Đỉnh / trên cùng, Top"},
{ko:"닦다", vi:"Lau / chùi, Wipe"},
{ko:"동안", vi:"Trong suốt (khoảng thời gian), During"},
{ko:"되다", vi:"Trở thành, Become"},
{ko:"마을", vi:"Làng, Village"},
{ko:"마지막", vi:"Cuối cùng, Last"},
{ko:"막걸리", vi:"Rượu gạo Hàn Quốc, Makgeolli"},
{ko:"모습", vi:"Hình dáng / dáng vẻ, Appearance"},

  
  
  
  
  
  
  
  
  
{ko:"과정", vi:"Khóa học, Course"},
{ko:"수업", vi:"Lớp học / buổi học, Class"},
{ko:"수업하다", vi:"Dạy học / lên lớp, Teach"},
{ko:"시작", vi:"Bắt đầu, Start"},
{ko:"안내하다", vi:"Hướng dẫn / thông báo, Guide / Inform"},
{ko:"오전", vi:"Buổi sáng (AM), Morning / AM"},
{ko:"오후", vi:"Buổi chiều (PM), Afternoon / PM"},
{ko:"요일", vi:"Thứ trong tuần, Day of the week"},
{ko:"음료수", vi:"Đồ uống, Beverage"},
{ko:"이번", vi:"Lần này, This time"},
{ko:"주간", vi:"Ban ngày / theo tuần, Daytime / Weekly"},
{ko:"야간", vi:"Ban đêm, Nighttime"},
{ko:"심야", vi:"Đêm khuya, Late night"},
{ko:"파티", vi:"Bữa tiệc, Party"},
{ko:"파티하다", vi:"Tổ chức / tham gia tiệc, Party"},
{ko:"회의", vi:"Cuộc họp, Meeting"},
{ko:"깨끗하다", vi:"Sạch sẽ, Clean"},
{ko:"근무", vi:"Ca làm / trực, Duty / Work shift"},
{ko:"근무하다", vi:"Làm việc / trực, Be on duty"},
{ko:"기상", vi:"Thức dậy, Wake-up"},
{ko:"기상하다", vi:"Thức dậy, Wake up"},
{ko:"체육", vi:"Thể dục / thể thao, Physical education"},
{ko:"대회", vi:"Đại hội / cuộc thi, Competition"},
{ko:"대화", vi:"Đối thoại / trò chuyện, Conversation"},
{ko:"식사", vi:"Bữa ăn, Meal"},
{ko:"식사하다", vi:"Ăn uống, Have a meal"},
{ko:"아내", vi:"Vợ, Wife"},
{ko:"외식", vi:"Ăn ngoài, Eating out"},
{ko:"외식하다", vi:"Đi ăn ngoài, Eat out"},
{ko:"인터넷", vi:"Internet, Internet"},
{ko:"일과", vi:"Sinh hoạt hằng ngày / lịch làm việc, Daily routine"},
{ko:"정도", vi:"Mức độ, Degree / Extent"},
{ko:"일상생활", vi:"Sinh hoạt thường ngày, Daily life"},
{ko:"자유", vi:"Tự do, Freedom"}, 
   
  /* Từ loại */
{ko:"명사", vi:"Danh từ, Noun"},
{ko:"대명사", vi:"Đại từ, Pronoun"},
{ko:"수사", vi:"Số từ, Numeral"},
{ko:"동사", vi:"Động từ, Verb"},
{ko:"형용사", vi:"Tính từ, Adjective"},
{ko:"부사", vi:"Trạng từ, Adverb"},
{ko:"관형사", vi:"Định từ, Determiner"},
{ko:"조사", vi:"Trợ từ, Particle"},










  
  /* Danh từ */
{ko:"안내", vi:"Hướng dẫn / thông báo, Guidance / Notice"},
{ko:"보고서", vi:"Báo cáo, Report"},
{ko:"올림", vi:"Kính gửi / trân trọng (kết thư), Respectfully (closing)"},
{ko:"높임말", vi:"Kính ngữ, Honorific language"},
{ko:"달리기", vi:"Chạy bộ, Running"},
{ko:"뛰기", vi:"Chạy, nhảy (bộc phát), Run"},
{ko:"야간", vi:"Ban đêm, Nighttime"},
{ko:"평일", vi:"Ngày trong tuần, Weekday"},

{ko:"교육", vi:"Giáo dục / đào tạo, Education / Training"},
{ko:"원장", vi:"Viện trưởng / hiệu trưởng (học viện), Director"},
{ko:"중요하다", vi:"Quan trọng, Important"},
{ko:"준비", vi:"Chuẩn bị, Preparation"},

{ko:"행사", vi:"Sự kiện, Event"},
{ko:"행사하다", vi:"Tổ chức sự kiện, Hold an event"},

{ko:"훈련", vi:"Huấn luyện, Training"},
{ko:"훈련하다", vi:"Huấn luyện, To train"},
{ko:"사격", vi:"Bắn súng, Shooting"},
{ko:"사격하다", vi:"Bắn súng, To shoot"},
{ko:"위병", vi:"Lính gác, Guard"},

{ko:"주변", vi:"Xung quanh, Surroundings"},
{ko:"입구", vi:"Lối vào, Entrance"},
{ko:"출구", vi:"Lối ra, Exit"},
{ko:"입교", vi:"Nhập học (vào trường/khóa huấn luyện), Enrollment / Admission"},
{ko:"입교하다", vi:"Nhập học / tham gia khóa huấn luyện, To enroll / be admitted"},

{ko:"동료", vi:"Đồng nghiệp / đồng đội, Colleague"},
{ko:"머리", vi:"Đầu / tóc, Head / Hair"},

{ko:"점심", vi:"Bữa trưa, Lunch"},
{ko:"저녁", vi:"Bữa tối, Dinner"},
{ko:"식료품", vi:"Thực phẩm / đồ ăn, Groceries"},
{ko:"신문", vi:"Báo, Newspaper"},
{ko:"편지", vi:"Thư, Letter"},
{ko:"구경", vi:"Tham quan / xem, Sightseeing"},
{ko:"자르다", vi:"Cắt, Cut"},

{ko:"등산", vi:"Leo núi, Hiking"},
{ko:"훈련", vi:"Huấn luyện, Training"},
{ko:"배우다", vi:"Học, Learn"},
{ko:"가르치다", vi:"Dạy, Teach"},
{ko:"끝나다", vi:"Kết thúc, End"},

{ko:"교육", vi:"Giáo dục / đào tạo, Education"},
{ko:"기간", vi:"Thời gian / thời hạn, Period"},
{ko:"문화", vi:"Văn hóa, Culture"},
{ko:"정보", vi:"Thông tin, Information"},

{ko:"내일", vi:"Ngày mai, Tomorrow"},
{ko:"매일", vi:"Mỗi ngày, Every day"},
{ko:"항상", vi:"Luôn luôn, Always"},
{ko:"다음주", vi:"Tuần sau, Next week"},
{ko:"매주", vi:"Hàng tuần, Every week"},
{ko:"기념일", vi:"Ngày kỷ niệm, Anniversary"},
{ko:"몇", vi:"Mấy / bao nhiêu, How many"},
{ko:"날씨", vi:"Thời tiết, Weather"},
{ko:"값", vi:"Giá tiền, Price"},
{ko:"전자", vi:"Điện tử, Electronic"},
{ko:"전기", vi:"Điện, Electricity"},
{ko:"복사기", vi:"Máy photocopy, Copier"},
{ko:"쿠키", vi:"Bánh quy / cookie, Cookie"},
{ko:"언덕", vi:"Đồi, Hill"},
{ko:"숲", vi:"Rừng, Forest"}, 
{ko:"도", vi:"Tỉnh / đạo, Province"},
{ko:"시", vi:"Thành phố, City"},
{ko:"군", vi:"Huyện (đơn vị hành chính), County"},
{ko:"읍", vi:"Thị trấn, Town"},
{ko:"면", vi:"Xã (đơn vị hành chính), Township"},
{ko:"동", vi:"Phường/khu phố/toà nhà, Neighborhood"},
{ko:"리", vi:"Làng (đơn vị hành chính nhỏ), Village unit"},  
{ko:"목소리", vi:"Giọng nói, Voice"},
{ko:"박수", vi:"Vỗ tay, Applause"},
{ko:"물품/물건", vi:"Vật phẩm / hàng hóa 물품(trang trọng), 물건(đời thường), Goods"},
{ko:"아까", vi:"Lúc nãy, A while ago"}, 
{ko:"정답", vi:"Đáp án đúng, Correct answer"},
{ko:"예문", vi:"Câu ví dụ, Example sentence"},
{ko:"의미", vi:"Ý nghĩa, Meaning"}, 
{ko:"그러면", vi:"Vậy thì / nếu vậy thì, Then"},
{ko:"는데/지만", vi:"Nhưng / tuy nhiên (liên kết câu), But / Though"},







  
  
 



  
  /* Quân đội & Cấp bậc */
{ko:"분대", vi:"Tiểu đội, Squad"},
{ko:"소대", vi:"Trung đội, Platoon"},
{ko:"중대", vi:"Đại đội, Company"},
{ko:"대대", vi:"Tiểu đoàn, Battalion"},
{ko:"연대", vi:"Trung đoàn, Regiment"},
{ko:"여단", vi:"Lữ đoàn, Brigade"},
{ko:"사단", vi:"Sư đoàn, Division"},
{ko:"군단", vi:"Quân đoàn, Corps"},
{ko:"군구", vi:"Quân khu, Military district"},
{ko:"군", vi:"Quân đội, Military"},
{ko:"국방부", vi:"Bộ Quốc phòng, Ministry of National Defense"},
{ko:"사령부", vi:"Bộ tư lệnh, Command headquarters"},
{ko:"계급", vi:"Cấp bậc, Rank"},
{ko:"군종", vi:"Quân chủng, Military branch"},
{ko:"장교", vi:"Sĩ quan, Officer"},
{ko:"장군", vi:"Tướng, General"},
{ko:"대장", vi:"Đại tướng, General of the army"},
{ko:"중장", vi:"Trung tướng, Lieutenant general"},
{ko:"소장", vi:"Thiếu tướng, Major general"},
{ko:"준장", vi:"Chuẩn tướng, Brigadier general"},
{ko:"대령", vi:"Đại tá, Colonel"},
{ko:"중령", vi:"Trung tá, Lieutenant colonel"},
{ko:"소령", vi:"Thiếu tá, Major"},
{ko:"대위", vi:"Đại úy, Captain"},
{ko:"중위", vi:"Trung úy, First lieutenant"},
{ko:"소위", vi:"Thiếu úy, Second lieutenant"},
{ko:"준위", vi:"Chuẩn úy, Warrant officer"},
{ko:"하사-중사-상사-원사", vi:"Hạ sĩ quan"},
{ko:"이병-일병-상병-병장", vi:"Binh nhì-Binh nhất-...."},
{ko:"생도", vi:"Học viên quân sự, Cadet"},
{ko:"소대장", vi:"Trung đội trưởng, Platoon leader"},
{ko:"부대", vi:"Đơn vị, Unit"},
{ko:"부대원", vi:"Quân nhân trong đơn vị, Unit member"},
{ko:"지휘관", vi:"Chỉ huy, Commander"},
{ko:"지휘관 명칭", vi:"Tên gọi chức vụ chỉ huy, Command title"},
{ko:"명령", vi:"Mệnh lệnh, Order"},
{ko:"경례", vi:"Chào (quân đội), Salute"},
{ko:"경례 구호", vi:"Khẩu lệnh chào, Salute command"},
{ko:"사격장", vi:"Trường bắn, Shooting range"},
{ko:"출타", vi:"Ra ngoài có phép, Authorized leave"},
{ko:"제대", vi:"Xuất ngũ, Discharge"},
{ko:"숙소", vi:"Nơi ở, Barracks"},
{ko:"군용품", vi:"Trang bị quân dụng, Military equipment"},

{ko:"군복", vi:"Quân phục, Military uniform"},
{ko:"군장", vi:"Quân trang, Military gear"},
{ko:"근무모", vi:"Mũ công vụ, Duty cap"},
{ko:"근무화", vi:"Giày công vụ, Duty shoes"},
{ko:"근무복", vi:"Quân phục công vụ, Duty uniform"},
{ko:"전투모", vi:"Mũ chiến đấu, Combat helmet"},
{ko:"전투복", vi:"Quân phục chiến đấu, Combat uniform"},
{ko:"전투화", vi:"Giày chiến đấu, Combat boots"},  
{ko:"위병소", vi:"Trạm gác, Guard post"},
{ko:"의무대", vi:"Quân y, Medical unit"},
  
 /* Vũ khí */ 
{ko:"무기", vi:"Vũ khí, Weapon"},
{ko:"장갑차", vi:"Xe bọc thép, Armored vehicle"},
{ko:"자주포", vi:"Pháo tự hành, Self-propelled artillery"},
{ko:"포", vi:"Pháo, Cannon"},
{ko:"폭탄", vi:"Bom, Bomb"},
{ko:"견인포", vi:"Pháo kéo, Towed artillery"},
{ko:"박격포", vi:"Súng cối, Mortar"},

  

{ko:"기자", vi:"Phóng viên, Reporter"},
{ko:"군인", vi:"Quân nhân, Soldier"},
{ko:"의사", vi:"Bác sĩ, Doctor"},
{ko:"간호사", vi:"Y tá, Nurse"},
{ko:"경찰", vi:"Cảnh sát, Police"},
{ko:"경찰관", vi:"Cảnh sát viên, Police officer"},
{ko:"변호사", vi:"Luật sư, Lawyer"},
{ko:"교수", vi:"Giáo sư, Professor"},
{ko:"선생님", vi:"Giáo viên / thầy cô, Teacher"},
{ko:"학생", vi:"Học sinh, sinh viên, Student"},
{ko:"가수", vi:"Ca sĩ, Singer"},
{ko:"배우", vi:"Diễn viên, Actor"},
{ko:"요리사", vi:"Đầu bếp, Chef"},
{ko:"농부", vi:"Nông dân, Farmer"},
{ko:"운전사", vi:"Tài xế, Driver"},
{ko:"조종사", vi:"Phi công, Pilot"},
{ko:"기술자", vi:"Kỹ thuật viên, Technician"},
{ko:"회사원", vi:"Nhân viên công ty, Office worker"},
{ko:"주부", vi:"Nội trợ, Housewife"},
{ko:"관리자", vi:"Quản lý, Manager"},
{ko:"주무관님", vi:"Quản lý chính"},

 {ko:"가족", vi:"Gia đình, Family"},
{ko:"부모님", vi:"Bố mẹ (kính ngữ), Parents"},
{ko:"아버지", vi:"Bố, cha, Father"},
{ko:"어머니", vi:"Mẹ, Mother"},
{ko:"엄마", vi:"Mẹ (thân mật), Mom"},
{ko:"오빠", vi:"Anh trai (nữ gọi), Older brother"},
{ko:"누나", vi:"Chị gái (nam gọi), Older sister"},
{ko:"언니", vi:"Chị gái (nữ gọi), Older sister (female speaker)"},
{ko:"동생", vi:"Em, Younger sibling"},
{ko:"삼촌", vi:"Chú, bác trai, Uncle"},
{ko:"이모", vi:"Dì, Aunt"},
{ko:"아저씨", vi:"Chú, bác (đàn ông trung niên), Mister"},
{ko:"아주머니", vi:"Cô, dì (phụ nữ trung niên), Madam"},
{ko:"호칭", vi:"Cách xưng hô, Form of address"},
{ko:"씨", vi:"Hậu tố xưng hô lịch sự, Polite suffix"},
{ko:"자기", vi:"Bản thân / anh-em (thân mật), Honey / Self"},
{ko:"내", vi:"Của tôi / tôi (dạng bổ nghĩa), My"},
{ko:"아들", vi:"Con trai, Son"},
{ko:"딸", vi:"Con gái, Daughter"},

{ko:"손님", vi:"Khách, Guest"},
{ko:"승객", vi:"Hành khách, Passenger"},
{ko:"한국인", vi:"Người Hàn Quốc, Korean"},
{ko:"아이", vi:"Trẻ em, Child"},
{ko:"남자", vi:"Nam giới, Man"},
{ko:"여자", vi:"Nữ giới, Woman"},

{ko:"나라", vi:"Đất nước, Country"},
{ko:"국가", vi:"Quốc gia, Nation"},
{ko:"국적", vi:"Quốc tịch, Nationality"},
{ko:"고향", vi:"Quê hương, Hometown"},
{ko:"도시", vi:"Thành phố, City"},
{ko:"동네", vi:"Khu phố / khu dân cư, Neighborhood"},
{ko:"장소", vi:"Địa điểm, Place"},
{ko:"공원", vi:"Công viên, Park"},
{ko:"학교", vi:"Trường học, School"},
{ko:"대학교", vi:"Trường đại học, University"},
{ko:"대학", vi:"Đại học, College"},
{ko:"중학교", vi:"Trường trung học cơ sở, Middle school"},
{ko:"교실", vi:"Phòng học, Classroom"},
{ko:"운동장", vi:"Sân thể thao, Playground"},
{ko:"체력 단련실", vi:"Phòng tập thể lực, Gym"},
{ko:"연병장", vi:"Sân tập quân sự, Parade ground"},
{ko:"도서관", vi:"Thư viện, Library"},
{ko:"서점", vi:"Hiệu sách, Bookstore"},
{ko:"미술관", vi:"Bảo tàng mỹ thuật, Art museum"},
{ko:"극장", vi:"Rạp hát / rạp chiếu phim, Theater / Cinema"},
{ko:"병원", vi:"Bệnh viện, Hospital"},
{ko:"약국", vi:"Nhà thuốc, Pharmacy"},
{ko:"은행", vi:"Ngân hàng, Bank"},
{ko:"우체국", vi:"Bưu điện, Post office"},
{ko:"대사관", vi:"Đại sứ quán, Embassy"},
{ko:"백화점", vi:"Trung tâm thương mại, Department store"},
{ko:"시장", vi:"Chợ, Market"},
{ko:"슈퍼마켓", vi:"Siêu thị, Supermarket"},
{ko:"매점", vi:"Cửa hàng nhỏ / căng tin, Convenience store"},
{ko:"미용실", vi:"Tiệm làm tóc, Hair salon"},
{ko:"이발소", vi:"Tiệm cắt tóc nam, Barbershop"},
{ko:"호텔", vi:"Khách sạn, Hotel"},
{ko:"기숙사", vi:"Ký túc xá, Dormitory"},
{ko:"사무실", vi:"Văn phòng, Office"},
{ko:"사무소", vi:"Văn phòng (hành chính), Office"},
{ko:"주차장", vi:"Bãi đỗ xe, Parking lot"},
{ko:"화장실", vi:"Nhà vệ sinh, Restroom"},
{ko:"술집", vi:"Quán rượu, Bar"},
{ko:"커피숍", vi:"Quán cà phê, Coffee shop"},
{ko:"경기장", vi:"Sân thi đấu / sân vận động, Stadium"},
{ko:"본관", vi:"Tòa nhà chính, Main building"},
{ko:"생활관", vi:"Khu sinh hoạt / doanh trại, Living quarters"},

{ko:"버스", vi:"Xe buýt, Bus"},
{ko:"택시", vi:"Taxi, Taxi"},
{ko:"기차", vi:"Tàu hỏa, Train"},
{ko:"지하철", vi:"Tàu điện ngầm dưới đất, Subway"},
{ko:"전철", vi:"Tàu điện thường trên mặt đất"},
{ko:"비행기", vi:"Máy bay, Airplane"},
{ko:"자동차", vi:"Ô tô, Car"},
{ko:"차", vi:"Xe, Vehicle"},
{ko:"자전거", vi:"Xe đạp, Bicycle"},
{ko:"역", vi:"Nhà ga, Station"},
{ko:"지하철역", vi:"Ga tàu điện ngầm, Subway station"},
{ko:"정류장", vi:"Trạm dừng, Stop"},
{ko:"요금소", vi:"Trạm thu phí, Toll booth"},
{ko:"승차", vi:"Lên xe, Boarding"},
{ko:"하차", vi:"Xuống xe, Getting off"},
{ko:"환승", vi:"Chuyển tuyến, Transfer"},
{ko:"출발", vi:"Xuất phát, Departure"},
{ko:"도착", vi:"Đến nơi, Arrival"},
{ko:"표", vi:"Vé, Ticket"},
{ko:"운전면허증", vi:"Bằng lái xe, Driver’s license"},

{ko:"냉장고", vi:"Tủ lạnh, Refrigerator"},
{ko:"냉동실", vi:"Ngăn đông, Freezer compartment"},
{ko:"냉장실", vi:"Ngăn mát, Refrigerator compartment"},
{ko:"세탁기", vi:"Máy giặt, Washing machine"},
{ko:"에어컨", vi:"Điều hòa, Air conditioner"},
{ko:"선풍기", vi:"Quạt điện, Electric fan"},
{ko:"다리미", vi:"Bàn ủi, Iron"},
{ko:"전화", vi:"Điện thoại, Telephone"},
{ko:"휴대폰", vi:"Điện thoại di động, Mobile phone"},
{ko:"핸드폰", vi:"Điện thoại di động, Cell phone"},
{ko:"컴퓨터", vi:"Máy tính, Computer"},
{ko:"텔레비전", vi:"Ti vi, Television"},
{ko:"라디오", vi:"Radio, Radio"},
{ko:"카메라", vi:"Máy ảnh, Camera"},
{ko:"시계", vi:"Đồng hồ, Clock / Watch"},

{ko:"부엌용품", vi:"Đồ dùng nhà bếp, Kitchen utensils"},
{ko:"그릇", vi:"Bát / tô, Bowl"},
{ko:"접시", vi:"Đĩa, Plate"},
{ko:"냄비", vi:"Nồi, Pot"},
{ko:"전기밥솥", vi:"Nồi cơm điện, Rice cooker"},
{ko:"프라이팬", vi:"Chảo, Frying pan"},
{ko:"도마", vi:"Thớt, Cutting board"},
{ko:"숟가락", vi:"Thìa, Spoon"},
{ko:"젓가락", vi:"Đũa, Chopsticks"},
{ko:"포크", vi:"Nĩa, Fork"},
{ko:"컵", vi:"Cốc, Cup"},

{ko:"비누", vi:"Xà phòng, Soap"},
{ko:"세탁 비누", vi:"Xà phòng giặt, Laundry soap"},
{ko:"세탁 세제", vi:"Bột/nước giặt, Laundry detergent"},
{ko:"주방 세제", vi:"Nước rửa chén, Dishwashing detergent"},
{ko:"샴푸", vi:"Dầu gội, Shampoo"},
{ko:"치약", vi:"Kem đánh răng, Toothpaste"},
{ko:"칫솔", vi:"Bàn chải đánh răng, Toothbrush"},
{ko:"면도기", vi:"Dao cạo, Razor"},
{ko:"휴지", vi:"Giấy vệ sinh, Toilet paper"},
{ko:"물티슈", vi:"Khăn ướt, Wet wipes"},
{ko:"수건", vi:"Khăn, Towel"},
{ko:"거울", vi:"Gương, Mirror"},
{ko:"향", vi:"Hương, nhang/ Mùi hương / hương thơm, Scent / Aroma"},
{ko:"빗자루", vi:"Chổi, Broom"},
{ko:"쓰레받기", vi:"Hót rác, Dustpan"},
{ko:"쓰레기통", vi:"Thùng rác, Trash can"},

{ko:"옷", vi:"Quần áo, Clothes"},
{ko:"옷장", vi:"Tủ quần áo, Wardrobe"},
{ko:"바지", vi:"Quần, Pants"},
{ko:"치마", vi:"Váy, Skirt"},
{ko:"스웨터", vi:"Áo len, Sweater"},
{ko:"모자", vi:"Mũ, Hat"},
{ko:"장갑", vi:"Găng tay, Gloves"},
{ko:"신발", vi:"Giày, Shoes"},
{ko:"구두", vi:"Giày da, Dress shoes"},
{ko:"슬리퍼", vi:"Dép lê, Slippers"},
{ko:"안경", vi:"Kính, Glasses"},
{ko:"선글라스", vi:"Kính râm, Sunglasses"},
{ko:"가방", vi:"Túi xách, Bag"},
{ko:"지갑", vi:"Ví, Wallet"},

{ko:"여권", vi:"Hộ chiếu, Passport"},
{ko:"열쇠", vi:"Chìa khóa, Key"},
{ko:"우산", vi:"Ô / dù, Umbrella"},
{ko:"반지", vi:"Nhẫn, Ring"},
{ko:"사물함", vi:"Tủ cá nhân, Locker"},
{ko:"소파", vi:"Ghế sofa, Sofa"},
{ko:"침대", vi:"Giường, Bed"},
{ko:"책상", vi:"Bàn học/làm việc, Desk"},
{ko:"의자", vi:"Ghế, Chair"},
{ko:"탁자", vi:"Bàn, Table"},
{ko:"운동화", vi:"Giày thể thao, Sneakers"},
{ko:"기구", vi:"Dụng cụ / thiết bị, Equipment"},
{ko:"사진", vi:"Ảnh, Photo"},

{ko:"밥", vi:"Cơm, Rice"},
{ko:"볶음밥", vi:"Cơm rang, Fried rice"},
{ko:"라면", vi:"Mì ăn liền, Instant noodles"},
{ko:"국수", vi:"Mì / bún, Noodles"},
{ko:"샌드위치", vi:"Bánh mì kẹp, Sandwich"},
{ko:"햄버거", vi:"Hamburger, Hamburger"},
{ko:"파스타", vi:"Mì Ý, Pasta"},
{ko:"김밥", vi:"Cơm cuộn rong biển, Gimbap"},
{ko:"비빔밥", vi:"Cơm trộn, Bibimbap"},
{ko:"죽", vi:"Cháo, Porridge"},
{ko:"떡", vi:"Bánh gạo, Rice cake"},
{ko:"빵", vi:"Bánh mì, Bread"},
{ko:"피자", vi:"Pizza, Pizza"},
{ko:"치킨", vi:"Gà rán, Fried chicken"},
{ko:"불고기", vi:"Thịt nướng, Bulgogi"},
{ko:"삼겹살", vi:"Thịt ba chỉ, Pork belly"},
{ko:"소고기", vi:"Thịt bò, Beef"},
{ko:"돼지고기", vi:"Thịt heo, Pork"},
{ko:"닭고기", vi:"Thịt gà, Chicken"},
{ko:"계란", vi:"Trứng, Egg"},
{ko:"달걀", vi:"Trứng (cách nói khác), Egg"},
{ko:"버터", vi:"Bơ, Butter"},
{ko:"채소", vi:"Rau, Vegetables"},
{ko:"샐러드", vi:"Salad, Salad"},
{ko:"국", vi:"Canh, Soup"},
{ko:"찌개", vi:"Canh hầm, Stew"},
{ko:"반찬", vi:"Món ăn kèm, Side dish"},
{ko:"삼계탕", vi:"Canh gà hầm sâm, Ginseng chicken soup"},
{ko:"고기", vi:"Thịt, Meat"},
{ko:"생선", vi:"Cá (món ăn), Fish"},
{ko:"물고기", vi:"Cá (con cá sống), Fish (living)"},
{ko:"굴", vi:"Hàu, Oyster"},
{ko:"민물고기", vi:"Cá nước ngọt, Freshwater fish"},
{ko:"고등어", vi:"Cá thu, Mackerel"},
{ko:"참치", vi:"Cá ngừ, Tuna"},
{ko:"연어", vi:"Cá hồi, Salmon"},
{ko:"새우", vi:"Tôm, Shrimp"},
{ko:"게", vi:"Cua, Crab"},
{ko:"오징어", vi:"Mực ống, Squid"},
{ko:"문어", vi:"Bạch tuộc, Octopus"},
{ko:"조개", vi:"Nghêu / sò, Clam"},
{ko:"미역", vi:"Rong biển, Seaweed"},
{ko:"과일", vi:"Trái cây, Fruit"},
{ko:"키위", vi:"Quả kiwi, Kiwi"},
{ko:"사과", vi:"Táo, Apple"},
{ko:"포도", vi:"Nho, Grape"},
{ko:"딸기", vi:"Dâu tây, Strawberry"},
{ko:"바나나", vi:"Chuối, Banana"},
{ko:"레몬", vi:"Chanh tây, Lemon"},
{ko:"수박", vi:"Dưa hấu, Watermelon"},
{ko:"배", vi:"Lê, Pear"},
{ko:"오렌지", vi:"Cam, Orange"},
{ko:"귤", vi:"Quýt, Mandarin"},
{ko:"망고", vi:"Xoài, Mango"},
{ko:"복숭아", vi:"Đào, Peach"},
{ko:"체리", vi:"Cherry"},
{ko:"양념", vi:"Gia vị đã pha/ đồ nêm, Seasoning"},
{ko:"조미료", vi:"Gia vị (chất điều vị), Seasoning / Condiment"},
{ko:"당근", vi:"Cà rốt, Carrot"},
{ko:"감자", vi:"Khoai tây, Potato"},
{ko:"오이", vi:"Dưa leo, Cucumber"},
{ko:"양배추", vi:"Bắp cải, Cabbage"},
{ko:"파", vi:"Hành lá, Green onion"},
{ko:"고추", vi:"Ớt, Chili pepper"},
{ko:"토마토", vi:"Cà chua, Tomato"},
{ko:"상추", vi:"Xà lách, Lettuce"},
{ko:"배추", vi:"Cải thảo, Napa cabbage"},
{ko:"브로콜리", vi:"Súp lơ, Broccoli"},
{ko:"가지", vi:"Cà tím, Eggplant"},
{ko:"콩", vi:"Đậu, Bean"},
{ko:"버섯", vi:"Nấm, Mushroom"},
{ko:"후추", vi:"Tiêu, Pepper"},
{ko:"소금", vi:"Muối, Salt"},
{ko:"설탕", vi:"Đường, Sugar"},
{ko:"꿀", vi:"Mật ong, Honey"},
{ko:"땅콩", vi:"Đậu phộng, Peanut"},
{ko:"간장", vi:"Nước tương, Soy sauce"},
{ko:"고추장", vi:"Tương ớt Hàn Quốc, Gochujang"},
{ko:"된장", vi:"Tương đậu nành, Soybean paste"},
{ko:"마늘", vi:"Tỏi, Garlic"},
{ko:"파", vi:"Hành lá, Green onion"},
{ko:"양파", vi:"Hành tây, Onion"},
{ko:"식초", vi:"Giấm, Vinegar"},
{ko:"기름", vi:"Dầu ăn, oil"},
{ko:"케이크", vi:"Bánh, Cake"},
{ko:"초콜릿", vi:"Sô-cô-la, Chocolate"},
{ko:"아이스크림", vi:"Kem, Ice cream"},
{ko:"시리얼", vi:"Ngũ cốc, Cereal"},
{ko:"물", vi:"Nước, Water"},
{ko:"주스", vi:"Nước ép, Juice"},
{ko:"커피", vi:"Cà phê, Coffee"},
{ko:"차", vi:"Trà, Tea"},
{ko:"술", vi:"Rượu, Alcohol"},
{ko:"맥주", vi:"Bia, Beer"},
{ko:"우유", vi:"Sữa, Milk"},
{ko:"두유", vi:"Sữa đậu nành, Soy milk"},
{ko:"콜라", vi:"Coca, Cola"},
{ko:"녹차", vi:"Trà xanh, Green tea"},
{ko:"홍차", vi:"Hồng trà, Black tea"},
{ko:"소주", vi:"Rượu soju, Soju"},
{ko:"와인", vi:"Rượu vang, Wine"},
{ko:"하루", vi:"Một ngày, One day"},
{ko:"아침", vi:"Buổi sáng, Morning"},
{ko:"낮", vi:"Ban ngày, Daytime"},
{ko:"밤", vi:"Ban đêm, Night"},
{ko:"오늘", vi:"Hôm nay, Today"},
{ko:"매일", vi:"Mỗi ngày, Every day"},
{ko:"요즘", vi:"Dạo này, These days"},
{ko:"주말", vi:"Cuối tuần, Weekend"},
{ko:"방학", vi:"Kỳ nghỉ (của học sinh, sinh viên), School vacation"},
{ko:"휴가", vi:"Kỳ nghỉ / nghỉ phép, Vacation"},
{ko:"일정", vi:"Lịch trình, Schedule"},
{ko:"전", vi:"Trước, Before"},
{ko:"후", vi:"Sau, After"},
{ko:"때", vi:"Lúc / khi, When"},
{ko:"시간", vi:"Thời gian / giờ, Time"},
{ko:"분", vi:"Vị, ngài(người), Phút, Minute"},
{ko:"월요일", vi:"Thứ hai, Monday"},
{ko:"화요일", vi:"Thứ ba, Tuesday"},
{ko:"수요일", vi:"Thứ tư, Wednesday"},
{ko:"목요일", vi:"Thứ năm, Thursday"},
{ko:"금요일", vi:"Thứ sáu, Friday"},
{ko:"토요일", vi:"Thứ bảy, Saturday"},
{ko:"일요일", vi:"Chủ nhật, Sunday"},

{ko:"봄", vi:"Mùa xuân, Spring"},
{ko:"여름", vi:"Mùa hè, Summer"},
{ko:"가을", vi:"Mùa thu, Autumn"},
{ko:"겨울", vi:"Mùa đông, Winter"},

{ko:"수", vi:"Số, Number"},
{ko:"수사", vi:"Số từ (ngữ pháp), Numeral"},
{ko:"단위", vi:"Đơn vị, Unit"},
{ko:"큰 수", vi:"Số lớn, Large number"},
{ko:"번호", vi:"Số thứ tự / số hiệu, Number"},

{ko:"가격", vi:"Giá cả, Price"},
{ko:"요금", vi:"Phí, Fee"},
{ko:"요금표", vi:"Bảng giá, Price list"},
{ko:"돈", vi:"Tiền, Money"},
{ko:"화폐", vi:"Tiền tệ, Currency"},

  /* Màu sắc */
  /* Tính từ */
{ko:"하얗다", vi:"Trắng, White"},
{ko:"검다", vi:"Đen, Black"},
{ko:"빨갛다", vi:"Đỏ, Red"},
{ko:"파랗다", vi:"Xanh dương, Blue"},
{ko:"노랗다", vi:"Vàng, Yellow"},
{ko:"분홍색이다", vi:"Hồng, Pink"},


  /* Danh từ màu sắc */
{ko:"흰색", vi:"Màu trắng, White color"},
{ko:"검은색", vi:"Màu đen, Black color"},
{ko:"검정색", vi:"Màu đen, Black color"},
{ko:"빨간색", vi:"Màu đỏ, Red color"},
{ko:"파란색", vi:"Màu xanh dương, Blue color"},
{ko:"노란색", vi:"Màu vàng, Yellow color"},
{ko:"초록색", vi:"Màu xanh lá, Green color"},
{ko:"주황색", vi:"Màu cam, Orange color"},
{ko:"보라색", vi:"Màu tím, Purple color"},
{ko:"분홍색", vi:"Màu hồng, Pink color"},
{ko:"갈색", vi:"Màu nâu, Brown color"},
{ko:"회색", vi:"Màu xám, Gray color"},
{ko:"하늘색", vi:"Màu xanh da trời nhạt, Sky blue"},
{ko:"남색", vi:"Màu xanh đậm (xanh hải quân), Navy blue"},
{ko:"금색", vi:"Màu vàng kim, Gold color"},
{ko:"은색", vi:"Màu bạc, Silver color"},





  /* Hoạt động – Thể thao – Giải trí */
  /* Thể thao */
{ko:"산책", vi:"Đi dạo, Walk"},

{ko:"수영", vi:"Bơi lội, Swimming"},
{ko:"운동", vi:"Tập thể dục, Exercise"},
{ko:"수영", vi:"Bơi lội, Swim"},
{ko:"노래", vi:"Hát, Sing"},
{ko:"댄스", vi:"Nhảy, Dance"},
{ko:"등산", vi:"Leo núi, Hiking"},
{ko:"쇼핑", vi:"Mua sắm, Shop"},
{ko:"축구", vi:"Bóng đá, Soccer"},
{ko:"농구", vi:"Bóng rổ, Basketball"},
{ko:"야구", vi:"Bóng chày, Baseball"},
{ko:"배구", vi:"Bóng chuyền, Volleyball"},
{ko:"테니스", vi:"Quần vợt, Tennis"},
{ko:"배드민턴", vi:"Cầu lông, Badminton"},
{ko:"요가", vi:"Yoga, Yoga"},
{ko:"게임하다", vi:"Chơi game, Play games"},
{ko:"영화보다", vi:"Xem phim, Watch a movie"},
{ko:"독서하다", vi:"Đọc sách, Read books"},
{ko:"사진 찍다", vi:"Chụp ảnh, Take photos"},

  /* Học tập & Ngôn ngữ */
{ko:"복습", vi:"Ôn tập, Review"},
{ko:"완성하다", vi:"Hoàn thành, To complete"},
{ko:"발표하다", vi:"Trình bày, To present"},
{ko:"표현", vi:"Biểu đạt, Expression"},
{ko:"문장", vi:"Câu văn, Sentence"},
{ko:"한글", vi:"Chữ Hàn, Hangul"},
{ko:"모음", vi:"Nguyên âm, Vowel"},
{ko:"자음", vi:"Phụ âm, Consonant"},
{ko:"받침", vi:"Phụ âm cuối, Final consonant"},
{ko:"문법", vi:"Ngữ pháp, Grammar"},
{ko:"어휘", vi:"Từ vựng, Vocabulary"},
{ko:"단원", vi:"Bài học / đơn vị bài, Unit"},
{ko:"주제", vi:"Chủ đề, Topic"},
{ko:"학습", vi:"Học tập, Learning"},
{ko:"활동", vi:"Hoạt động, Activity"},
{ko:"교재", vi:"Giáo trình, Textbook"},
{ko:"본문", vi:"Nội dung chính (bài đọc), Main text"},
{ko:"글", vi:"Bài viết / văn bản, Text"},
{ko:"구성", vi:"Cấu trúc, Structure"},
{ko:"구성하다", vi:"Cấu thành / sắp xếp, Organize"},
{ko:"소개", vi:"Giới thiệu, Introduction"},
{ko:"시험", vi:"Kỳ thi, Exam"},
{ko:"숙제", vi:"Bài tập về nhà, Homework"},
{ko:"연습", vi:"Luyện tập, Practice"},

/* Thông tin & Giao tiếp */
{ko:"상황", vi:"Tình huống, Situation"},
{ko:"정보", vi:"Thông tin, Information"},
{ko:"공지", vi:"Thông báo, Notice"},
{ko:"공지 사항", vi:"Thông báo (chung), Announcement"},
{ko:"이메일", vi:"Email, Email"},
{ko:"약속", vi:"Cuộc hẹn / lời hứa, Appointment / Promise"},
{ko:"문화", vi:"Văn hóa, Culture"},
{ko:"관련", vi:"Liên quan, Related"},
{ko:"대답", vi:"Câu trả lời, Answer"},
{ko:"주소", vi:"Địa chỉ, Address"},
{ko:"연결하다", vi:"Kết nối, Connect"},


  /* Đồ dùng học tập */
{ko:"종이", vi:"Giấy, Paper"},
{ko:"필통", vi:"Hộp bút, Pencil case"},
{ko:"연필", vi:"Bút chì, Pencil"},
{ko:"볼펜", vi:"Bút bi, Ballpoint pen"},
{ko:"지우개", vi:"Cục tẩy, Eraser"},
{ko:"공책", vi:"Vở, Notebook"},
{ko:"자", vi:"Thước kẻ, Ruler"},
{ko:"가위", vi:"Kéo, Scissors"},
{ko:"사전", vi:"Từ điển, Dictionary"},
 
  /* Khác */
{ko:"가짜", vi:"Giả, Fake"},
{ko:"꿈", vi:"Giấc mơ, Dream"},
{ko:"실수", vi:"Sơ suất, Mistake"},
{ko:"잘못", vi:"Lỗi / điều sai, Fault"},
 
  /* Thiên nhiên */
{ko:"별", vi:"Ngôi sao, Star"},
{ko:"꽃", vi:"Hoa, Flower"},
{ko:"나무", vi:"Cây, Tree"},
{ko:"하늘", vi:"Bầu trời, Sky"},
{ko:"구름", vi:"Mây, Cloud"},
{ko:"해, 태양", vi:"Mặt trời, Sun"},
{ko:"달", vi:"Mặt trăng, Moon"},
{ko:"비", vi:"Mưa, Rain"},
{ko:"눈", vi:"Mắt/Eye, Tuyết/Snow"},
{ko:"바람", vi:"Gió, Wind"},
{ko:"산", vi:"Núi, Mountain"},
{ko:"강", vi:"Sông, River"},
{ko:"바다", vi:"Biển, Sea"},
{ko:"숲", vi:"Rừng, Forest"},

  /* Động vật */
{ko:"고래", vi:"Cá voi, Whale"},
{ko:"코끼리", vi:"Con voi, Elephant"},
{ko:"거미", vi:"Con nhện, Spider"},
{ko:"강아지", vi:"Chó con, Puppy"},
{ko:"고양이", vi:"Con mèo, Cat"},
{ko:"새", vi:"Mới/New, Chim/Bird"},
{ko:"말", vi:"Ngựa, Horse"},
{ko:"소", vi:"Bò, Cow"},
{ko:"돼지", vi:"Heo, Pig"},
{ko:"닭", vi:"Gà, Chicken"},

/* Vị trí */
{ko:"위치", vi:"Vị trí, Position"},
{ko:"층", vi:"Tầng, Floor"},
{ko:"밑", vi:"Bên dưới, Under"},
{ko:"옆", vi:"Bên cạnh, Next to"},
{ko:"맞은편", vi:"Đối diện, Opposite"},
{ko:"건너편", vi:"Bên kia / đối diện, Across / Opposite"},
{ko:"위", vi:"Phía trên, Above"},
{ko:"아래", vi:"Phía dưới, Below"},
{ko:"앞", vi:"Phía trước, Front"},
{ko:"뒤", vi:"Phía sau, Back"},
{ko:"근처", vi:"Gần đây / gần đó, Nearby"},
{ko:"안", vi:"Bên trong, Inside"},
{ko:"밖", vi:"Bên ngoài, Outside"},
{ko:"가운데", vi:"Ở tâm, Middle"},
{ko:"한강", vi:"Sông Hàn, Han River"},
{ko:"건물", vi:"Tòa nhà, Building"},
{ko:"생활관", vi:"Khu sinh hoạt / doanh trại, Living quarters"},
{ko:"근처", vi:"Gần đây / khu vực gần, Nearby"},
{ko:"행선지", vi:"Điểm đến, Destination"}, 

/* Phương hướng */
{ko:"방향", vi:"Hướng, Direction"},
{ko:"왼쪽, 좌측", vi:"Bên trái, Left"},
{ko:"오른쪽, 우측", vi:"Bên phải, Right"},











  

  
  


/* Động từ */
{ko:"가다", vi:"Đi, Go"},
{ko:"오다", vi:"Đến, Come"},
{ko:"내리다", vi:"Xuống / hạ, Get off / Lower"},
{ko:"타다", vi:"Lên (xe), Ride"},
{ko:"운전하다", vi:"Lái xe, Drive"},
{ko:"조종하다", vi:"Điều khiển, Control"},
{ko:"걷다", vi:"Đi bộ, Walk"},
{ko:"뛰다", vi:"Chạy, nhảy (bộc phát), Run"},
{ko:"달리다", vi:"Chạy (liên tục), Run"},
{ko:"건너다", vi:"Băng qua, Cross"},
{ko:"들어가다", vi:"Đi vào, Enter"},
{ko:"나오다", vi:"Đi ra, Come out"},
{ko:"돌아가다", vi:"Quay về, Return"},
{ko:"이동하다", vi:"Di chuyển, Move"},
{ko:"출발하다", vi:"Khởi hành, Depart"},
{ko:"도착하다", vi:"Đến nơi, Arrive"},
{ko:"지나가다", vi:"Đi ngang qua, Pass by"},
{ko:"운동하다", vi:"Tập thể dục, Exercise"},
{ko:"수영하다", vi:"Bơi lội, Swim"},
{ko:"노래하다", vi:"Hát, Sing"},

{ko:"먹다", vi:"Ăn, Eat"},
{ko:"마시다", vi:"Uống, Drink"},
{ko:"자다", vi:"Ngủ, Sleep"},
{ko:"쉬다", vi:"Nghỉ ngơi, Rest"},
{ko:"목욕하다", vi:"Tắm (bồn), Take a bath"},
{ko:"샤워하다", vi:"Tắm (vòi sen), Shower"},
{ko:"청소하다", vi:"Dọn dẹp, Clean"},
{ko:"요리하다", vi:"Nấu ăn, Cook"},
{ko:"설거지하다", vi:"Rửa bát, Wash dishes"},
{ko:"빨래하다", vi:"Giặt đồ, Do laundry"},
{ko:"다림질하다", vi:"Là ủi, Iron clothes"},
{ko:"일어나다", vi:"Thức dậy, Wake up"},
{ko:"잠자다", vi:"Ngủ, Sleep"},
{ko:"세수하다", vi:"Rửa mặt, Wash face"},
{ko:"양치하다", vi:"Đánh răng, Brush teeth"},
{ko:"화장하다", vi:"Trang điểm, Put on makeup"},
{ko:"옷을 입다", vi:"Mặc quần áo, Get dressed"},
{ko:"옷을 벗다", vi:"Cởi quần áo, Take off clothes"},
{ko:"집에 가다", vi:"Về nhà, Go home"},
{ko:"집에 오다", vi:"Đến nhà, Come home"},
{ko:"고장나다", vi:"Bị hỏng, Break down"},
{ko:"끄다", vi:"Tắt, Turn off"},
{ko:"켜다", vi:"Bật, Turn on"},
{ko:"반하다", vi:"Phải lòng / bị cuốn hút, Fall for"},
{ko:"팔로우", vi:"Theo dõi (mạng xã hội), Follow"},
{ko:"플러팅", vi:"Tán tỉnh, Flirting"},
{ko:"쇼핑하다", vi:"Mua sắm, Shop"},
{ko:"구매하다", vi:"Mua (trang trọng), Purchase"},
{ko:"사다", vi:"Mua, Buy"},
 
{ko:"일하다", vi:"Làm việc, Work"},
{ko:"공부하다", vi:"Học tập, Study"},
{ko:"준비하다", vi:"Chuẩn bị, Prepare"},
{ko:"시작하다", vi:"Bắt đầu, Start"},
{ko:"표현하다", vi:"Biểu đạt, Express"},
{ko:"생각하다", vi:"Nghĩ, Think"},
{ko:"이해하다", vi:"Hiểu, Understand"},
{ko:"알다", vi:"Biết, Know"},

{ko:"말하다", vi:"Nói, Speak"},
{ko:"이야기", vi:"Câu chuyện / nói chuyện, Story / Talk"},
{ko:"묻다", vi:"Hỏi, Ask"},
{ko:"대답하다", vi:"Trả lời, Answer"},
{ko:"답하다", vi:"Trả lời (trang trọng), Reply"},
{ko:"인사하다", vi:"Chào hỏi, Greet"},
{ko:"만나다", vi:"Gặp, Meet"},
{ko:"확인하다", vi:"Xác nhận / kiểm tra, Confirm / Check"},













  



  /* Tính từ */
{ko:"짧다", vi:"Ngắn, Short"},
{ko:"길다", vi:"Dài, Long"},
{ko:"넓다", vi:"Rộng, Wide"},
{ko:"좁다", vi:"Hẹp, Narrow"},
{ko:"높다", vi:"Cao, High"},
{ko:"낮다", vi:"Thấp, Low"},
{ko:"크다", vi:"To, Big"},
{ko:"작다", vi:"Nhỏ, Small"},
{ko:"무겁다", vi:"Nặng, Heavy"},
{ko:"가볍다", vi:"Nhẹ, Light"},
{ko:"두껍다", vi:"Dày, Thick"},
{ko:"얇다", vi:"Mỏng, Thin"},
{ko:"차갑다", vi:"Lạnh, Cold"},
{ko:"뜨겁다", vi:"Nóng, Hot"},
{ko:"느리다", vi:"Chậm, Slow"},
{ko:"멋있다", vi:"Đẹp trai, Cool"},
{ko:"무섭다", vi:"Sợ hãi, Scary"},
{ko:"어렵다", vi:"Khó, Difficult"},
{ko:"쉽다", vi:"Dễ, Easy"},
{ko:"밝다", vi:"Sáng, Bright"},
{ko:"어둡다", vi:"Tối, Dark"},
{ko:"시끄럽다", vi:"Ồn ào, Noisy"},
{ko:"조용하다", vi:"Yên tĩnh, Quiet"},
{ko:"많다", vi:"Nhiều, Many"},
{ko:"적다", vi:"Ít, Few"},
 
{ko:"걱정하다", vi:"Lo lắng, Worry"},
{ko:"기다리다", vi:"Chờ đợi, Wait"},
{ko:"잊어버리다", vi:"Quên, To forget"},
{ko:"잃어버리다", vi:"Làm mất, To lose"},
{ko:"실수하다", vi:"Mắc lỗi (vô ý), Make a mistake"},
{ko:"잘못하다", vi:"Làm sai, Do wrong"},
{ko:"대하다", vi:"Đối xử / đối diện, To treat / face"},
{ko:"같다", vi:"Giống, Same / Similar"},
{ko:"이상", vi:"Trở lên / bất thường, Above / Abnormal"},

  /* Tri giác */
{ko:"보다", vi:"Xem / nhìn, See / Watch"},
{ko:"보이다", vi:"Được nhìn thấy, Be seen"},
{ko:"듣다", vi:"Nghe, Listen"},
{ko:"읽다", vi:"Đọc, Read"},
{ko:"쓰다", vi:"Viết / dùng, Write / Use"},

  /* Tính từ – Miêu tả */
{ko:"좋다", vi:"Tốt, Good"},
{ko:"나쁘다", vi:"Xấu, Bad"},
{ko:"크다", vi:"To, lớn, Big"},
{ko:"큰", vi:"To, lớn (bổ nghĩa), Big (modifier)"},
{ko:"작다", vi:"Nhỏ, Small"},
{ko:"길다", vi:"Dài, Long"},
{ko:"짧다", vi:"Ngắn, Short"},
{ko:"많다", vi:"Nhiều, Many"},
{ko:"없다", vi:"Không có, Not exist"},
{ko:"바쁘다", vi:"Bận, Busy"},
{ko:"즐겁다", vi:"Vui vẻ, Joyful"},
{ko:"기쁘다", vi:"Vui mừng, Glad"},
{ko:"심심하다", vi:"Buồn chán, Bored"},
{ko:"화나다", vi:"Tức giận, Angry"},
{ko:"어렵다", vi:"Khó, Difficult"},
{ko:"멀다", vi:"Xa, Far"},
{ko:"무겁다", vi:"Nặng, Heavy"},
{ko:"덥다", vi:"Nóng, Hot"},
{ko:"아름답다", vi:"Đẹp, Beautiful"},
{ko:"건강하다", vi:"Khỏe mạnh, Healthy"},
{ko:"맛있다", vi:"Ngon, Delicious"},
{ko:"불편하다", vi:"Bất tiện, Uncomfortable"},
{ko:"편하다", vi:"Thoải mái, Comfortable"},
{ko:"쉽다", vi:"Dễ, Easy"},
{ko:"귀엽다", vi:"Dễ thương, Cute"},

  /* Biểu hiện & mức độ */
{ko:"어떻다", vi:"Như thế nào, How"},
{ko:"어떠하다", vi:"Như thế nào (trang trọng), How (formal)"},
{ko:"천천히 하다", vi:"Làm chậm rãi, Do slowly"},















  


  
 /* Trạng từ */
{ko:"꼭", vi:"Nhất định / 꼭, 반드시, Surely / 반드시"},
{ko:"아주", vi:"Rất, Very"},
{ko:"너무", vi:"Quá / rất, Too / Very"},
{ko:"엄청", vi:"Cực kỳ / rất nhiều, Extremely"},
{ko:"미리", vi:"Trước, In advance"},
{ko:"그냥", vi:"Cứ / đơn giản là, Just"},
{ko:"약간", vi:"Hơi / một chút, Slightly"},
{ko:"이런", vi:"Như thế này, Like this"},
{ko:"그렇게", vi:"Như vậy, Like that"},
{ko:"같이", vi:"Cùng nhau, Together"},
{ko:"열심히", vi:"Chăm chỉ, Diligently"},
{ko:"많이", vi:"Nhiều, A lot"},
{ko:"조금", vi:"Ít / một chút, A little"},
{ko:"빨리", vi:"Nhanh, Quickly"},
{ko:"천천히", vi:"Chậm rãi, Slowly"},
{ko:"자주", vi:"Thường xuyên, Often"},
{ko:"가끔", vi:"Thỉnh thoảng, Sometimes"},
{ko:"항상", vi:"Luôn luôn, Always"},
{ko:"벌써", vi:"Đã rồi, Already"},
{ko:"아직", vi:"Vẫn chưa, Still / Yet"},
{ko:"다시", vi:"Lại / lại lần nữa, Again"},
{ko:"마음대로", vi:"Theo ý mình, As one pleases"},
{ko:"갑자기", vi:"Đột nhiên, Suddenly"},
{ko:"아마", vi:"Có lẽ, Probably"}

];
