var WORDS = [
{ko:"본문", vi:"Phần nội dung chính (bài viết, văn bản)"},
{ko:"시리얼", vi:"Ngũ cốc (cereal)"},
{ko:"꿀", vi:"Mật ong"},
{ko:"샌드위치", vi:"Bánh mì kẹp"},
{ko:"버터", vi:"Bơ"},
{ko:"땅콩", vi:"Đậu phộng"},
{ko:"대답", vi:"Câu trả lời"},
{ko:"주소", vi:"Địa chỉ"},
{ko:"주무관님", vi:"Chuyên viên (cách gọi lịch sự trong cơ quan nhà nước)"},
{ko:"연습", vi:"Luyện tập"},
{ko:"연결하다", vi:"Kết nối, nối, liên lạc"},
{ko:"답하다", vi:"Trả lời (trang trọng)"},
{ko:"대답하다", vi:"Trả lời"},
{ko:"원사", vi:"Nguyên sĩ (quân hàm hạ sĩ quan cao cấp)"},
{ko:"상사", vi:"Thượng sĩ"},
{ko:"중사", vi:"Trung sĩ"},
{ko:"하사", vi:"Hạ sĩ (quân đội Hàn Quốc)"},
{ko:"병장", vi:"Binh nhất (cấp cao nhất của binh sĩ)"},
{ko:"상병", vi:"Nhất binh"},
{ko:"일병", vi:"Nhị binh"},
{ko:"이병", vi:"Binh nhì"},
{ko:"장교", vi:"Officer"},
{ko:"준위", vi:"Chuẩn uý"},
{ko:"소위", vi:"Thiếu uý"},
{ko:"중위", vi:"Trung uý"},
{ko:"대위", vi:"Captain"},
{ko:"소령", vi:"Thiếu tá"},
{ko:"중령", vi:"Trung tá"},
{ko:"대령", vi:"Colonel"},
{ko:"장군", vi:"Sĩ quan cấp tướng"},
{ko:"준장", vi:"Chuẩn tướng"},
{ko:"소장", vi:"Thiếu tướng"},
{ko:"중장", vi:"Trung tướng"},
{ko:"대장", vi:"Đại tướng"},
{ko:"생도", vi:"Cadet"},
{ko:"국적", vi:"Quốc tịch"},
{ko:"국가", vi:"Quốc gia / nhà nước, Dùng khi: văn bản hành chính, chính trị, pháp luật, báo chí"},
{ko:"구성하다", vi:"Cấu thành, sắp xếp, tổ chức"},
{ko:"교재", vi:"Giáo trình, tài liệu học"},
{ko:"구성", vi:"Cấu trúc"},
{ko:"하얗다", vi:"Trắng"},
{ko:"검다", vi:"Đen"},
{ko:"빨갛다", vi:"Đỏ"},
{ko:"파랗다", vi:"Xanh dương"},
{ko:"노랗다", vi:"Vàng"},
{ko:"초록색이다 / 초록이다", vi:"Là màu xanh lá"},
{ko:"분홍색이다", vi:"Là màu hồng"},
{ko:"흰색", vi:"Màu trắng"},
{ko:"파란색", vi:"Màu xanh dương"},
{ko:"노란색", vi:"Màu vàng"},
{ko:"초록색", vi:"Màu xanh lá"},
{ko:"주황색", vi:"Màu cam"},
{ko:"보라색", vi:"Màu tím"},
{ko:"분홍색", vi:"Màu hồng"},
{ko:"검은색", vi:"Màu đen"},
{ko:"승차", vi:"Lên xe/ Dùng khi thông báo"},
{ko:"하차", vi:"Xuống xe/ Dùng khi thông báo"},
{ko:"코끼리", vi:"Con voi"},
{ko:"정류장", vi:"Trạm dừng"},
{ko:"역", vi:"Ga"},
{ko:"출발", vi:"Xuất phát"},
{ko:"도착", vi:"Đến nơi"},
{ko:"환승", vi:"Chuyển tuyến"},
{ko:"표", vi:"Vé"},
{ko:"승객", vi:"Hành khách"},
{ko:"운전사", vi:"Tài xế"},
{ko:"공식", vi:"Chính thức, công thức, 공식 명칭: tên chính thức, 수학 공식: công thức toán học"},
{ko:"명칭", vi:"Tên gọi, danh xưng (trang trọng), 이 제품의 명칭은 무엇입니까?/Tên gọi của sản phẩm này là gì?"},
{ko:"성함", vi:"Tên (kính ngữ, dùng lịch sự)/성함이 어떻게 되세요?/Quý danh của ngài là gì?"},
{ko:"엄청", vi:"Rất, cực kỳ"},
{ko:"예약하다", vi:"Đặt trước, đặt chỗ"},
{ko:"미리", vi:"Trước"},
{ko:"이런", vi:"Như thế này"},
{ko:"화나다", vi:"Tức giận"},
{ko:"요즘", vi:"Dạo này"},
{ko:"요금", vi:"Phí, tiền cước"},
{ko:"요금소", vi:"Trạm thu phí"},
{ko:"요금표", vi:"Bảng giá, bảng phí"},
{ko:"천천히 하다", vi:"Chậm rãi"},
{ko:"어떻다", vi:"Như thế nào"},
{ko:"어떠하다", vi:"Như thế nào (trang trọng hơn)"},
{ko:"그냥", vi:"Cứ, đơn giản là"},
{ko:"약간", vi:"Hơi, một chút"},
{ko:"그렇게", vi:"Như vậy"},
{ko:"실수", vi:"Sơ suất, lỗi vô ý"},
{ko:"실수하다", vi:"Mắc lỗi do bất cẩn"},
{ko:"잘못", vi:"Lỗi, điều sai"},
{ko:"잘못하다", vi:"Làm sai, làm không đúng"},
{ko:"장갑차", vi:"Armored Vehicle/xe bọc thép"},
{ko:"자주포", vi:"Self-Propelled Artillery/ Pháo tự hành"},
{ko:"앞", vi:"Phía trước"},
{ko:"뒤", vi:"Phía sau"},
{ko:"옆", vi:"Bên cạnh"},
{ko:"왼쪽", vi:"Bên trái"},
{ko:"장소", vi:"Địa điểm"},
{ko:"동네", vi:"Khu phố / Xóm"},
{ko:"고향", vi:"Quê hương"},
{ko:"하루", vi:"Một ngày"},
{ko:"주말", vi:"Cuối tuần"},
{ko:"일정", vi:"Lịch trình"},
{ko:"약속", vi:"Cuộc hẹn"},
{ko:"표현하다", vi:"Diễn đạt / Thể hiện"},
{ko:"이메일", vi:"Email"},
{ko:"공지", vi:"Thông báo"},
{ko:"공지 사항", vi:"Nội dung, mục thông báo"},
{ko:"전에", vi:"Trước khi"},
{ko:"후에", vi:"Sau khi"},
{ko:"때", vi:"Khi / Lúc"},
{ko:"일과", vi:"Công việc hằng ngày"},
{ko:"휴가", vi:"Kỳ nghỉ / Nghỉ phép"},
{ko:"한국인", vi:"Người Hàn Quốc"},
{ko:"호칭", vi:"Cách xưng hô"},
{ko:"수", vi:"Số / Số lượng"},
{ko:"가격", vi:"Giá cả"},
{ko:"화폐", vi:"Tiền tệ"},
{ko:"수사", vi:"Số từ"},
{ko:"단위", vi:"Đơn vị"},
{ko:"큰 수", vi:"Số lớn"},
{ko:"부대", vi:"Đơn vị quân đội"},
{ko:"부대원", vi:"Quân nhân"},
{ko:"지휘관", vi:"Chỉ huy"},
{ko:"지휘관 명칭", vi:"Chức danh chỉ huy"},
{ko:"부대 시설물", vi:"Cơ sở vật chất quân đội"},
{ko:"군용품", vi:"Vật dụng quân đội"},
{ko:"포", vi:"Pháo"},
{ko:"사격장", vi:"Trường bắn"},
{ko:"경례", vi:"Chào quân đội"},
{ko:"경례 구호", vi:"Khẩu hiệu chào"},
{ko:"출타", vi:"Việc đi ra ngoài (có phép)"},
{ko:"폭탄", vi:"Bom"},
{ko:"제대", vi:"Xuất ngũ"},
{ko:"세탁 비누", vi:"Laundry Soap"},
{ko:"세탁 세제", vi:"Laundry Detergent/ Xà phòng giặt"},
{ko:"주방 세제", vi:"Dishwashing Liquid/ Nước rửa chén"},
{ko:"물티슈", vi:"Wet Wipes/ Khăn ướt"},
{ko:"냉동실", vi:"Freezer Compartment/ Ngăn đông"},
{ko:"냉장실", vi:"Refrigerator Compartment/ Ngăn mát"},
{ko:"그릇", vi:"Rice Bowl"},
{ko:"접시", vi:"Plate/ Đĩa"},
{ko:"냄비", vi:"Pot/ Nồi"},
{ko:"전기밥솥", vi:"Rice Cooker/ Nồi cơm điện"},
{ko:"프라이팬", vi:"Frying Pan/ Chảo chiên"},
{ko:"도마", vi:"Cutting Board/ Thớt"},
{ko:"선풍기", vi:"Electric Fan"},
{ko:"사용하다", vi:"To Use"},
{ko:"인사하다", vi:"To Greet"},
{ko:"이해하다", vi:"To Understand"},
{ko:"자기", vi:"Yourself"},
{ko:"족장", vi:"Tribal Chief/ Tộc trưởng"},
{ko:"반장", vi:"Lớp trưởng"},
{ko:"관리자", vi:"Manager / Quản lý"},
{ko:"조종사", vi:"Pilot"},
{ko:"조종하다", vi:"To Control"},
{ko:"운전하다", vi:"To Drive"},
{ko:"운전면허증", vi:"Driver’s License"},
{ko:"쇼핑하다", vi:"To Shop"},
{ko:"구매하다", vi:"To Shop/ Dùng trang trọng"},
{ko:"사무실/사무소", vi:"Office"},
{ko:"묻다", vi:"To Ask/To Bury/Hỏi/Chôn"},
{ko:"솟다", vi:"từ dưới → vọt / trồi lên. Dùng cho nước, mầm cây, cảm xúc, ý tưởng/새싹이 땅에서 솟다/Mầm non mọc lên từ đất/온천이 여기저기서 솟는다/Suối nước nóng trồi lên khắp nơi"},
{ko:"같다", vi:"To Be The Same/"},
{ko:"국방", vi:"National Defense"},
{ko:"학원", vi:"Private Academy"},
{ko:"과학", vi:"Science"},
{ko:"찌르다", vi:"Đâm, chọc bằng vật nhọn"},
{ko:"고추", vi:"Chili/ Ớt"},
{ko:"후추", vi:"Pepper"},
{ko:"선글라스", vi:"Sunglasses"},
{ko:"아저씨", vi:"Uncle (informal)"},
{ko:"삼촌", vi:"Uncle/ Chưa lấy vợ"},
{ko:"이모", vi:"Aunt (mother’s side)"},
{ko:"아주머니", vi:"Madam / Auntie"},
{ko:"크다", vi:"Big / Large"},
{ko:"계급", vi:"Rank"},
{ko:"군종", vi:"Branch of military/ Quân chủng"},
{ko:"처음", vi:"First / Beginning"},
{ko:"인사", vi:"Greeting / Personnel"},
{ko:"위치", vi:"Location / Position"},
{ko:"물건", vi:"Item / Object/ Đồ vật"},
{ko:"숙소", vi:"Doanh trại"},
{ko:"글", vi:"Text / Writing/ Bài viết nói chung"},
{ko:"한식", vi:"Korean food"},
{ko:"무기", vi:"Weapon/ Vũ khí"},
{ko:"가방", vi:"Bag"},
{ko:"가을", vi:"Autumn"},
{ko:"가위", vi:"Scissors"},
{ko:"가짜", vi:"Fake"},
{ko:"가족", vi:"Family"},
{ko:"한글", vi:"Korean alphabet"},
{ko:"소개", vi:"Introduction"},
{ko:"단원", vi:"Unit / Lesson"},
{ko:"주제", vi:"Topic"},
{ko:"학습", vi:"Learning / Study"},
{ko:"활동", vi:"Activity"},
{ko:"문법", vi:"Grammar"},
{ko:"문화", vi:"Culture"},
{ko:"군", vi:"Military / Army"},
{ko:"관련", vi:"Related"},
{ko:"어휘", vi:"Vocabulary"},
{ko:"모음", vi:"Vowel"},
{ko:"자음", vi:"Consonant"},
{ko:"받침", vi:"Final consonant (batchim)"},
{ko:"당근", vi:"Carrot"},
{ko:"감자", vi:"Potato"},
{ko:"감사합니다", vi:"Thank you"},
{ko:"강아지", vi:"Puppy"},
{ko:"같이", vi:"Together"},
{ko:"개", vi:"Dog"},
{ko:"게임", vi:"Game"},
{ko:"거미", vi:"Spider"},
{ko:"거울", vi:"Mirror"},
{ko:"걷다", vi:"Walk"},
{ko:"검정색", vi:"Black color"},
{ko:"빨간색", vi:"Red color"},
{ko:"갈색", vi:"Brown"},
{ko:"걱정하다", vi:"Worry"},
{ko:"건강하다", vi:"Healthy"},
{ko:"걸어가다", vi:"Go by walking"},
{ko:"겨울", vi:"Winter"},
{ko:"결혼", vi:"Marriage"},
{ko:"경찰", vi:"Police"},
{ko:"고기", vi:"Meat"},
{ko:"고래", vi:"Whale"},
{ko:"고맙습니다", vi:"Thank you"},
{ko:"고양이", vi:"Cat"},
{ko:"공부하다", vi:"Study"},
{ko:"공책", vi:"Note book/ Vở"},
{ko:"공원", vi:"Park"},
{ko:"공항", vi:"Airport"},
{ko:"과일", vi:"Fruit"},
{ko:"교실", vi:"Classroom"},
{ko:"교회", vi:"Church"},
{ko:"구두", vi:"Leather Shoes"},
{ko:"국수", vi:"Noodles"},
{ko:"군인", vi:"Soldier"},
{ko:"굴", vi:"Oyster/ Con hàu"},
{ko:"귀", vi:"Ear"},
{ko:"그림", vi:"Picture"},
{ko:"극장", vi:"Theater / Cinema"},
{ko:"금요일", vi:"Friday"},
{ko:"기다리다", vi:"Wait"},
{ko:"기쁘다", vi:"Glad"},
{ko:"기숙사", vi:"Dormitory/ Ký túc xá"},
{ko:"기차", vi:"Train"},
{ko:"길다", vi:"Long"},
{ko:"꽃", vi:"Flower"},
{ko:"컴퓨터", vi:"Computer"},
{ko:"나쁘다", vi:"Bad"},
{ko:"나라", vi:"Nước/đất nước, Dùng khi: Nói chung về một đất nước, cảm xúc, văn hóa, con người"},
{ko:"나무", vi:"Tree"},
{ko:"나이/연세/살", vi:"Age"},
{ko:"남자", vi:"Male"},
{ko:"낮", vi:"Daytime"},
{ko:"내리다", vi:"Get off / Descend"},
{ko:"너", vi:"You"},
{ko:"너무", vi:"Too / Very"},
{ko:"네", vi:"Yes"},
{ko:"노래", vi:"Song"},
{ko:"노래하다", vi:"Sing"},
{ko:"농부", vi:"Farmer"},
{ko:"눈", vi:"Eye / Snow"},
{ko:"누나", vi:"Older sister (for male)"},
{ko:"다리", vi:"Leg / Bridge"},
{ko:"다음", vi:"Next"},
{ko:"달걀/ 계란", vi:"Egg"},
{ko:"달력", vi:"Calendar"},
{ko:"닭", vi:"Chicken"},
{ko:"대사관", vi:"Embassy"},
{ko:"대학교", vi:"Trường đại học"},
{ko:"대학", vi:"Đại học"},
{ko:"댄스", vi:"Dance"},
{ko:"덥다", vi:"Hot"},
{ko:"도서관", vi:"Library"},
{ko:"도시", vi:"City/ Đô thị"},
{ko:"도착하다", vi:"Arrive"},
{ko:"돈", vi:"Money"},
{ko:"동물", vi:"Animal"},
{ko:"동생", vi:"Younger sibling"},
{ko:"돼지", vi:"Pig"},
{ko:"드라마", vi:"Drama"},
{ko:"듣다", vi:"Listen"},
{ko:"등산", vi:"Hiking"},
{ko:"딸기", vi:"Strawberry"},
{ko:"라디오", vi:"Radio"},
{ko:"라면", vi:"Ramen"},
{ko:"러시아", vi:"Russia"},
{ko:"레몬", vi:"Lemon"},
{ko:"마늘", vi:"Garlic"},
{ko:"마시다", vi:"Drink"},
{ko:"마음", vi:"Heart / Mind/ Tấm lòng"},
{ko:"만나다", vi:"Meet/ Gặp"},
{ko:"많다", vi:"Many / A lot"},
{ko:"말", vi:"Word / Speech / Horse"},
{ko:"말하다", vi:"Speak"},
{ko:"맛있다", vi:"Delicious"},
{ko:"매일", vi:"Every day"},
{ko:"맥주", vi:"Beer"},
{ko:"머리", vi:"Head"},
{ko:"먹다", vi:"Eat"},
{ko:"멀다", vi:"Far"},
{ko:"명령", vi:"Command"},
{ko:"모자", vi:"Hat / Cap"},
{ko:"목", vi:"Neck"},
{ko:"목욕하다", vi:"Take a bath"},
{ko:"몸", vi:"Body"},
{ko:"무겁다", vi:"Heavy"},
{ko:"무릎", vi:"Knee"},
{ko:"무슨", vi:"Which"},
{ko:"문", vi:"Door"},
{ko:"물", vi:"Water"},
{ko:"물고기", vi:"Fish"},
{ko:"미국", vi:"USA"},
{ko:"미술관", vi:"Art museum"},
{ko:"미용실", vi:"Beauty salon"},
{ko:"바나나", vi:"Banana"},
{ko:"바쁘다", vi:"Busy"},
{ko:"바다", vi:"Sea"},
{ko:"바지", vi:"Pants"},
{ko:"밖", vi:"Outside"},
{ko:"반갑다", vi:"Glad to meet"},
{ko:"반지", vi:"Ring"},
{ko:"발", vi:"Foot"},
{ko:"밤", vi:"Night"},
{ko:"밥", vi:"Cooked rice"},
{ko:"방", vi:"Room"},
{ko:"방학", vi:"School vacation"},
{ko:"배", vi:"Pear / Boat / Stomach"},
{ko:"배우", vi:"Actor"},
{ko:"백화점", vi:"Department store"},
{ko:"버스", vi:"Bus"},
{ko:"번호", vi:"Number"},
{ko:"별", vi:"Star"},
{ko:"보내다", vi:"Send"},
{ko:"보다", vi:"See"},
{ko:"볼펜", vi:"Pen"},
{ko:"보이다", vi:"Be seen / Visible"},
{ko:"볶음밥", vi:"Fried rice/ Cơm chiên"},
{ko:"봄", vi:"Spring"},
{ko:"부엌", vi:"Kitchen"},
{ko:"부모님", vi:"Parents"},
{ko:"부엌용품", vi:"Kitchenware"},
{ko:"북", vi:"North/Drum"},
{ko:"분", vi:"Minute / Person"},
{ko:"불고기", vi:"Bulgogi/ Thịt nướng"},
{ko:"불편하다", vi:"Uncomfortable"},
{ko:"비누", vi:"Soap"},
{ko:"비행기", vi:"Airplane"},
{ko:"빗자루", vi:"Broom/ Chổi"},
{ko:"빵", vi:"Bread"},
{ko:"사과", vi:"Apple"},
{ko:"사다", vi:"Buy"},
{ko:"사물함", vi:"Tủ có khoá"},
{ko:"사랑", vi:"Love"},
{ko:"사랑하다", vi:"Love"},
{ko:"사진", vi:"Photo"},
{ko:"사전", vi:"Dictionary"},
{ko:"사업", vi:"Business"},
{ko:"산", vi:"Mountain"},
{ko:"살다", vi:"Live"},
{ko:"삼계탕", vi:"Ginseng chicken soup/ Gà hầm"},
{ko:"새", vi:"Bird / New"},
{ko:"생각하다", vi:"Think"},
{ko:"생선", vi:"Fish"},
{ko:"생일", vi:"Birthday"},
{ko:"생활", vi:"Sinh hoạt"},
{ko:"샤워하다", vi:"Shower"},
{ko:"서점", vi:"Bookstore"},
{ko:"서울", vi:"Seoul"},
{ko:"선물", vi:"Gift"},
{ko:"선생님", vi:"Teacher"},
{ko:"설탕", vi:"Sugar"},
{ko:"세탁기", vi:"Washing machine"},
{ko:"소고기", vi:"Beef"},
{ko:"소금", vi:"Salt"},
{ko:"소리", vi:"Sound"},
{ko:"소설", vi:"Novel/Tiểu thuyết"},
{ko:"소파", vi:"Sofa"},
{ko:"소풍", vi:"Picnic"},
{ko:"손", vi:"Hand"},
{ko:"손님", vi:"Guest"},
{ko:"수건", vi:"Towel"},
{ko:"수영하다", vi:"Swim"},
{ko:"수영장", vi:"Swimming pool"},
{ko:"수박", vi:"Watermelon"},
{ko:"숙제", vi:"Homework"},
{ko:"숟가락", vi:"Spoon"},
{ko:"술", vi:"Alcohol"},
{ko:"쉬다", vi:"Rest"},
{ko:"스웨터", vi:"Sweater/ Áo len"},
{ko:"시간", vi:"Time"},
{ko:"시장", vi:"Market"},
{ko:"시계", vi:"Clock / Watch"},
{ko:"시작하다", vi:"Start"},
{ko:"시험", vi:"Exam"},
{ko:"신문", vi:"Newspaper"},
{ko:"신발", vi:"Shoes"},
{ko:"싫어하다", vi:"Dislike / Hate"},
{ko:"심심하다", vi:"Bored"},
{ko:"쓰다", vi:"Write / Use / Bitter"},
{ko:"쓰레받기", vi:"Hót rác"},
{ko:"쓰레기통", vi:"Thùng rác"},
{ko:"씨", vi:"Seed / Mr./Ms."},
{ko:"아니요", vi:"No"},
{ko:"아름답다", vi:"Beautiful"},
{ko:"아래", vi:"Below"},
{ko:"아버지", vi:"Father"},
{ko:"아이", vi:"Child"},
{ko:"아이스크림", vi:"Ice cream"},
{ko:"아주", vi:"Very"},
{ko:"아침", vi:"Morning"},
{ko:"안녕하세요", vi:"Hello"},
{ko:"않다", vi:"Not"},
{ko:"알다", vi:"Know"},
{ko:"약국", vi:"Pharmacy"},
{ko:"양배추", vi:"Cabbage"},
{ko:"어머니", vi:"Mother"},
{ko:"어렵다", vi:"Difficult"},
{ko:"엄마", vi:"Mom"},
{ko:"없다", vi:"None / Not have"},
{ko:"여기", vi:"Here"},
{ko:"여권", vi:"Hộ chiếu"},
{ko:"에어컨", vi:"Điều hoà"},
{ko:"여름", vi:"Summer"},
{ko:"여자", vi:"Woman / Female"},
{ko:"연필", vi:"Pencil"},
{ko:"열다", vi:"Open"},
{ko:"열심히", vi:"Diligently/ Chăm chỉ"},
{ko:"영화", vi:"Movie"},
{ko:"오늘", vi:"Today"},
{ko:"오른쪽", vi:"Right"},
{ko:"오빠", vi:"Older brother (for female)"},
{ko:"오이", vi:"Cucumber"},
{ko:"우리", vi:"We / Us"},
{ko:"운동하다", vi:"Exercise"},
{ko:"운동장", vi:"Playground / Stadium"},
{ko:"월요일", vi:"Monday"},
{ko:"위", vi:"Above / Stomach"},
{ko:"유리", vi:"Glass"},
{ko:"은행", vi:"Bank"},
{ko:"음악", vi:"Music"},
{ko:"의사", vi:"Doctor"},
{ko:"의자", vi:"Chair/ Ghế"},
{ko:"이", vi:"Tooth / This"},
{ko:"이것", vi:"This"},
{ko:"이름", vi:"Name"},
{ko:"이발소", vi:"Barbershop"},
{ko:"이야기", vi:"Story / Talk"},
{ko:"일", vi:"Work / Day"},
{ko:"일하다", vi:"Work"},
{ko:"일요일", vi:"Sunday"},
{ko:"읽다", vi:"Read"},
{ko:"자다", vi:"Sleep"},
{ko:"자전거", vi:"Bicycle"},
{ko:"자동차", vi:"Car"},
{ko:"작다", vi:"Small"},
{ko:"잘하다", vi:"Do well"},
{ko:"장갑", vi:"Gloves"},
{ko:"전화", vi:"Phone"},
{ko:"점심", vi:"Lunch"},
{ko:"좋다", vi:"Good"},
{ko:"죄송합니다", vi:"Sorry"},
{ko:"주스", vi:"Juice"},
{ko:"주차장", vi:"Parking lot"},
{ko:"죽다", vi:"Die"},
{ko:"준비하다", vi:"Prepare"},
{ko:"중학교", vi:"Middle school"},
{ko:"즐겁다", vi:"Joyful"},
{ko:"지갑", vi:"Wallet"},
{ko:"지도", vi:"Bản đồ"},
{ko:"지하철", vi:"Subway"},
{ko:"직업", vi:"Job"},
{ko:"지우개", vi:"Cục tẩy"},
{ko:"짧다", vi:"Short"},
{ko:"차", vi:"Car / Tea"},
{ko:"차다", vi:"Kick / Wear (watch)"},
{ko:"창문", vi:"Window"},
{ko:"책", vi:"Book"},
{ko:"책상", vi:"Desk"},
{ko:"청소하다", vi:"Clean"},
{ko:"초콜릿", vi:"Chocolate"},
{ko:"축구", vi:"Soccer"},
{ko:"치마", vi:"Skirt"},
{ko:"침대", vi:"Bed"},
{ko:"칠판", vi:"Black board/ Bảng"},
{ko:"카메라", vi:"Camera"},
{ko:"커피", vi:"Coffee"},
{ko:"컵", vi:"Cup"},
{ko:"케이크", vi:"Cake"},
{ko:"코", vi:"Nose"},
{ko:"큰", vi:"Big"},
{ko:"키", vi:"Height"},
{ko:"타다", vi:"Ride"},
{ko:"탁자", vi:"Table"},
{ko:"택시", vi:"Taxi"},
{ko:"테니스", vi:"Tennis"},
{ko:"텔레비전", vi:"Television"},
{ko:"퇴근하다", vi:"Leave work"},
{ko:"파", vi:"Green onion / Leek"},
{ko:"파리", vi:"Fly / Paris"},
{ko:"파스타", vi:"Pasta"},
{ko:"팬", vi:"Pan/ Fan/ Quạt/ Người hâm mộ"},
{ko:"편하다", vi:"Comfortable"},
{ko:"포도", vi:"Grape"},
{ko:"포크", vi:"Fork"},
{ko:"피아노", vi:"Piano"},
{ko:"학교", vi:"School"},
{ko:"학생", vi:"Student"},
{ko:"햄버거", vi:"Hamburger"},
{ko:"행복", vi:"Happiness"},
{ko:"호수", vi:"Lake"},
{ko:"호텔", vi:"Hotel"},
{ko:"화장실", vi:"Bathroom / Toilet"},
{ko:"화요일", vi:"Tuesday"},
{ko:"회사", vi:"Company"},
{ko:"휴대폰", vi:"Mobile phone"},
{ko:"옷", vi:"Clothes"},
{ko:"옷장", vi:"Tủ quần áo"},
{ko:"샴푸", vi:"Shampoo"},
{ko:"치약", vi:"Kem đánh răng"},
{ko:"칫솔", vi:"Toothbrush"},
{ko:"휴지", vi:"Toilet paper/ Tissue"},
{ko:"우산", vi:"Umbrella"},
{ko:"열쇠", vi:"Key"},
{ko:"안경", vi:"Kính"},
{ko:"냉장고", vi:"Tủ lạnh"},
{ko:"다리미", vi:"Bàn là"},
{ko:"젓가락", vi:"Chopsticks"},
{ko:"핸드폰", vi:"Điện thoại"},
{ko:"면도기", vi:"Dao cạo râu"},
{ko:"가수", vi:"Singer"},
{ko:"주부", vi:"Housewife"},
{ko:"요리사", vi:"Chef/ Đầu bếp"},
{ko:"회사원", vi:"Nhân viên công ty"},
{ko:"간호사", vi:"Nurse"},
{ko:"경찰관", vi:"Cảnh sát"},
{ko:"미용사", vi:"Thợ cắt tóc, làm đẹp"},
{ko:"변호사", vi:"Lawyer"},
{ko:"운동선수", vi:"Vận động viên thể dục"},
{ko:"기술자", vi:"Engineer"},
{ko:"교수", vi:"Giáo sư"},
{ko:"술집", vi:"Tiệm bán rượu/ Bar"},
{ko:"우체국", vi:"Post office"},
{ko:"커피숍", vi:"Coffee shop"},
{ko:"슈퍼마켓", vi:"Super market"},
{ko:"지하철역", vi:"Ga tàu điện"},
{ko:"매점", vi:"Small Store"}
];
